import type { Question } from "@/content/types";

/** Band 1 and 2 for the Backend & scale lane, the last one to reach the lane
 *  bar of four. It is the largest lane at thirteen topics, and holds five of
 *  the twelve specialist depth topics. See easy-lanes-a.ts for why lanes sit
 *  at four where the spine sits at six. */
export const questions: Question[] = [
  {
    id: "ez-stor-001",
    type: "mcq",
    track: "system-design",
    topic: "storage",
    difficulty: 1,
    prompt: "What is object storage?",
    options: [
      { id: "a", text: "A store of files addressed by key, with no folders underneath" },
      { id: "b", text: "A disk attached to one machine that the operating system mounts" },
      { id: "c", text: "A database optimised for storing large binary values in rows" },
      { id: "d", text: "A cache holding recently downloaded files close to the user" },
    ],
    answer: "a",
    explanation:
      "Key to blob: effectively unlimited, cheap, durable, and high-latency per request. The flat namespace surprises people — paths with slashes are a naming convention rather than real directories, which is why listing a large prefix is slower than a filesystem would be.",
    concepts: ["Object storage", "Key-value addressing", "Blob storage"],
    tags: ["basics"],
  },
  {
    id: "ez-stor-002",
    type: "mcq",
    track: "system-design",
    topic: "storage",
    difficulty: 2,
    prompt: "Why keep the file in object storage and only the key in the database?",
    options: [
      { id: "a", text: "Blobs bloat every backup and evict useful pages from the cache" },
      { id: "b", text: "Databases cannot store binary data of more than a few megabytes" },
      { id: "c", text: "Object storage is the only place a file can be served publicly" },
      { id: "d", text: "Keys are indexed faster than the binary data they point at" },
    ],
    answer: "a",
    explanation:
      "Every backup now carries the images, restores get slower, and the buffer cache fills with bytes no query reads. A database is good at rows you filter and join; a two-megabyte photo is neither. Store the key and the metadata, and let object storage hold the bytes.",
    concepts: ["Object storage", "Buffer cache", "BLOB"],
    tags: ["modelling"],
  },
  {
    id: "ez-bp-002",
    type: "mcq",
    track: "system-design",
    topic: "backpressure",
    difficulty: 1,
    prompt: "What happens to an unbounded queue when work arrives faster than it leaves?",
    options: [
      { id: "a", text: "It grows until memory or patience runs out, hiding the overload" },
      { id: "b", text: "It automatically slows the producers down to the consumer's rate" },
      { id: "c", text: "It discards the oldest items to make room for the newest ones" },
      { id: "d", text: "It splits across more consumers so the rate evens out again" },
    ],
    answer: "a",
    explanation:
      "An unbounded queue does not absorb overload, it conceals it — right up to the point where everything fails at once, and most of the backlog is work whose callers gave up long ago. A bounded queue that rejects fails sooner, more honestly, and recovers faster.",
    concepts: ["Bounded queue", "Back pressure", "Queue depth"],
    tags: ["basics"],
  },
  {
    id: "ez-bp-003",
    type: "mcq",
    track: "system-design",
    topic: "backpressure",
    difficulty: 2,
    prompt: "Why is a timeout necessary on every outbound call?",
    options: [
      { id: "a", text: "Without one a slow dependency holds your threads until you fail too" },
      { id: "b", text: "The network will otherwise keep the connection open indefinitely" },
      { id: "c", text: "Timeouts are what trigger the retry that will eventually succeed" },
      { id: "d", text: "Without one the caller cannot tell success from failure at all" },
    ],
    answer: "a",
    explanation:
      "A call with no timeout waits forever while holding a thread and a connection. Enough of them and you have no capacity left — your service has died of somebody else's problem. A timeout converts their outage into your degraded response, which is the only version you control.",
    concepts: ["Timeout", "Thread pool exhaustion", "Cascading failure"],
    tags: ["timeouts"],
  },
  {
    id: "ez-anti-001",
    type: "mcq",
    track: "system-design",
    topic: "antipatterns",
    difficulty: 1,
    prompt: "Why is making many small requests often slower than one large one?",
    options: [
      { id: "a", text: "Each request pays the round trip, and those add up fast" },
      { id: "b", text: "Small requests are given a lower priority by the network" },
      { id: "c", text: "Servers process large payloads more efficiently per byte" },
      { id: "d", text: "Each request has to open an entirely new TCP connection" },
    ],
    answer: "a",
    explanation:
      "Two hundred calls at five milliseconds each is a full second, and the payload size never entered into it. That is chatty I/O, and the tell is exactly this shape: tiny data, fast network, slow page. Batch them, or issue them concurrently.",
    concepts: ["Chatty I/O", "Round-trip latency", "Request batching"],
    tags: ["latency"],
  },
  {
    id: "ez-rl-001",
    type: "mcq",
    track: "system-design",
    topic: "rate-limiting",
    difficulty: 1,
    prompt: "What is rate limiting for?",
    options: [
      { id: "a", text: "Capping how much one caller can consume of a shared service" },
      { id: "b", text: "Making sure that requests are handled in the order they arrived" },
      { id: "c", text: "Spreading traffic evenly across the available backend servers" },
      { id: "d", text: "Slowing responses down so the client has time to process them" },
    ],
    answer: "a",
    explanation:
      "Protection from a caller consuming more than their share — whether that is abuse, a buggy client stuck in a retry loop, or one tenant crowding out the rest. It is about fairness and survival, rather than ordering or distribution, which are different mechanisms entirely.",
    concepts: ["Rate limiting", "Quota", "Noisy neighbour"],
    tags: ["basics"],
  },
  {
    id: "ez-rl-002",
    type: "mcq",
    track: "system-design",
    topic: "rate-limiting",
    difficulty: 2,
    prompt: "Why does a token bucket allow bursts?",
    options: [
      { id: "a", text: "Unused capacity accumulates as tokens, up to a fixed cap" },
      { id: "b", text: "It counts the requests per minute rather than per second" },
      { id: "c", text: "It queues the excess requests rather than rejecting them" },
      { id: "d", text: "It raises the limit automatically when traffic increases" },
    ],
    answer: "a",
    explanation:
      "Tokens refill at a steady rate and sit in the bucket until spent, so a client that has been quiet has credit to spend at once. That usually matches what an API wants: a burst while syncing fifty records is legitimate, sustained traffic at that rate is not.",
    concepts: ["Token bucket", "Burst capacity", "Leaky bucket"],
    tags: ["algorithms"],
  },
  {
    id: "ez-arch-002",
    type: "mcq",
    track: "system-design",
    topic: "arch-patterns",
    difficulty: 1,
    prompt: "What does a sidecar do?",
    options: [
      { id: "a", text: "Runs supporting behaviour in a process beside the main service" },
      { id: "b", text: "Handles requests when the main service has failed its checks" },
      { id: "c", text: "Stores the configuration that the main service reads at start" },
      { id: "d", text: "Duplicates the main service so traffic can be split between them" },
    ],
    answer: "a",
    explanation:
      "Cross-cutting work — TLS, retries, telemetry — lifted out of the application and into a process deployed alongside it. Every service gets the behaviour without every service implementing it, in whatever language it happens to be written. The cost is another process per instance.",
    concepts: ["Sidecar pattern", "Cross-cutting concern", "Service mesh"],
    tags: ["patterns"],
  },
  {
    id: "ez-arch-003",
    type: "mcq",
    track: "system-design",
    topic: "arch-patterns",
    difficulty: 2,
    prompt: "What does the strangler fig pattern describe?",
    options: [
      { id: "a", text: "Replacing a system piece by piece, routing each part as it moves" },
      { id: "b", text: "Wrapping a legacy system in an API and then leaving it there" },
      { id: "c", text: "Running the old and new systems and comparing their outputs" },
      { id: "d", text: "Freezing the old system while the replacement is built beside it" },
    ],
    answer: "a",
    explanation:
      "A routing layer in front sends migrated paths to the new system and everything else to the old, until nothing is left to route. Every step ships and every step is reversible — which is what a big-bang rewrite cannot offer, having no working intermediate state.",
    concepts: ["Strangler fig pattern", "Incremental migration", "Facade"],
    tags: ["migration"],
  },
  {
    id: "ez-schema-001",
    type: "mcq",
    track: "data-enterprise",
    topic: "schema-design",
    difficulty: 1,
    prompt: "What does normalising a database mean?",
    options: [
      { id: "a", text: "Storing each fact once, and referring to it from everywhere else" },
      { id: "b", text: "Converting all the values in a column to a consistent format" },
      { id: "c", text: "Splitting one large table across several machines using a key" },
      { id: "d", text: "Adding indexes so that the common queries run more quickly" },
    ],
    answer: "a",
    explanation:
      "One fact, one place. A customer's address lives in the customers table and orders point at it, so changing it changes it everywhere and there is no second copy to disagree. Denormalising deliberately reverses that for read speed, taking on the consistency job in exchange.",
    concepts: ["Normalisation", "Denormalisation", "Referential integrity"],
    tags: ["basics"],
  },
  {
    id: "ez-mig-002",
    type: "mcq",
    track: "data-enterprise",
    topic: "migrations",
    difficulty: 1,
    prompt: "What is a database migration?",
    options: [
      { id: "a", text: "A versioned, repeatable change to the database's structure" },
      { id: "b", text: "The act of moving a database from one provider to another" },
      { id: "c", text: "Copying production data down into a development environment" },
      { id: "d", text: "Upgrading the database engine to a newer major release" },
    ],
    answer: "a",
    explanation:
      "A schema change written as code, versioned with the application, and applied in order. That is what makes an environment reproducible: a fresh database plus every migration equals production's shape. The word also means moving a database, which is a different job entirely.",
    concepts: ["Database migration", "Schema versioning", "Reproducible environment"],
    tags: ["basics"],
  },
  {
    id: "ez-mig-003",
    type: "mcq",
    track: "data-enterprise",
    topic: "migrations",
    difficulty: 2,
    prompt: "Why should a migration and the code that needs it deploy separately?",
    options: [
      { id: "a", text: "During a rolling deploy both versions of the code run at once" },
      { id: "b", text: "Migrations take longer to apply than a deploy takes to finish" },
      { id: "c", text: "The database cannot accept writes while a migration is running" },
      { id: "d", text: "Deploy tooling cannot run migrations and start services together" },
    ],
    answer: "a",
    explanation:
      "A rolling deploy has old and new instances serving simultaneously against one database, so the schema has to satisfy both. Ship the additive change, then the code using it, then the cleanup — three deploys each safe alone, rather than one that is safe only if nothing overlaps.",
    concepts: ["Rolling deployment", "Expand and contract", "Backwards compatibility"],
    tags: ["safety"],
  },
  {
    id: "ez-dbsec-002",
    type: "mcq",
    track: "data-enterprise",
    topic: "db-security",
    difficulty: 1,
    prompt: "Why give an application its own database user rather than the admin one?",
    options: [
      { id: "a", text: "A compromise then gets only what that one account could do" },
      { id: "b", text: "The admin account is rate limited by the database engine itself" },
      { id: "c", text: "Separate users make the query logs much easier to read later" },
      { id: "d", text: "The admin account cannot be used from outside the server" },
    ],
    answer: "a",
    explanation:
      "Least privilege bounds a breach rather than preventing one. An application account that reads two tables and writes one gives an attacker exactly that; the admin account gives them everything, including the ability to drop it all. Attribution is a real bonus, not the reason.",
    concepts: ["Principle of least privilege", "Database role", "Blast radius"],
    tags: ["basics"],
  },
  {
    id: "ez-shard-003",
    type: "mcq",
    track: "system-design",
    topic: "sharding",
    difficulty: 1,
    prompt: "What problem does sharding solve?",
    options: [
      { id: "a", text: "One machine no longer fitting or keeping up with the data" },
      { id: "b", text: "One machine failing and taking the whole system down with it" },
      { id: "c", text: "Queries running slowly because the right indexes are missing" },
      { id: "d", text: "Data needing to sit close to users in different regions" },
    ],
    answer: "a",
    explanation:
      "Capacity — the dataset outgrowing one machine's disk, memory, or write throughput. Surviving a failure is replication, which copies rather than splits, and the two are usually combined. Reach for sharding last: unsharding is far harder than sharding.",
    concepts: ["Sharding", "Replication", "Horizontal scaling"],
    tags: ["basics"],
  },
  {
    id: "ez-shard-004",
    type: "mcq",
    track: "system-design",
    topic: "sharding",
    difficulty: 2,
    prompt: "Why is a timestamp a poor shard key?",
    options: [
      { id: "a", text: "New rows all carry recent values, so one shard takes every write" },
      { id: "b", text: "Timestamps are not unique, so two rows can collide on the key" },
      { id: "c", text: "Time zones make one instant hash to several different shards" },
      { id: "d", text: "Timestamps cannot be compared once the data has been split" },
    ],
    answer: "a",
    explanation:
      "A monotonically increasing key sends everything new to whichever shard owns the newest range, so you get the operational cost of sharding with none of the write scaling. Hash the key, or prefix it with something high-cardinality, so today's writes land everywhere.",
    concepts: ["Hotspot", "Shard key", "Range partitioning"],
    tags: ["keys"],
  },
  {
    id: "ez-cdn-003",
    type: "mcq",
    track: "system-design",
    topic: "cdn",
    difficulty: 1,
    prompt: "What does Cache-Control: max-age do?",
    options: [
      { id: "a", text: "Says how long a cache may reuse the response before checking" },
      { id: "b", text: "Says how long the server will keep on generating this response" },
      { id: "c", text: "Says how old a cached copy may become before it is deleted" },
      { id: "d", text: "Says how long the browser should wait before the first request" },
    ],
    answer: "a",
    explanation:
      "The freshness window. Within it a cache serves its copy without asking; past it, the copy is stale and needs revalidating. Everything else in caching — s-maxage for shared caches, stale-while-revalidate for background refresh — is a refinement on that one number.",
    concepts: ["Cache-Control", "max-age", "Revalidation"],
    tags: ["headers"],
  },
  {
    id: "ez-cdn-004",
    type: "mcq",
    track: "system-design",
    topic: "cdn",
    difficulty: 2,
    prompt: "Why is a hash in a filename better than purging the CDN?",
    options: [
      { id: "a", text: "New content gets a new URL, so there is nothing stale to purge" },
      { id: "b", text: "Purging is not supported by the majority of delivery networks" },
      { id: "c", text: "Hashed filenames compress more effectively when in transit" },
      { id: "d", text: "A hash lets the CDN verify the file was not modified in transit" },
    ],
    answer: "a",
    explanation:
      "A purge is slow and eventually consistent across hundreds of edges, and you have to remember to issue it. A content hash sidesteps invalidation entirely: the URL changes whenever the bytes do, so you cache for a year and purge nothing except the HTML pointing at it.",
    concepts: ["Content-addressed URL", "Cache busting", "Immutable caching"],
    tags: ["invalidation"],
  },
  {
    id: "ez-search-003",
    type: "mcq",
    track: "system-design",
    topic: "search",
    difficulty: 1,
    prompt: "What is an inverted index?",
    options: [
      { id: "a", text: "A map from each term to the documents that contain it" },
      { id: "b", text: "An index stored in reverse order so that scanning is faster" },
      { id: "c", text: "A copy of the database that is kept purely for reading" },
      { id: "d", text: "An index built on the results of a query rather than a table" },
    ],
    answer: "a",
    explanation:
      "The inversion is the point. A document knows its own words; an inverted index knows each word's documents — so a multi-term query becomes looking up two lists and intersecting them, rather than reading every document to see what it contains.",
    concepts: ["Inverted index", "Full-text search", "Tokenisation"],
    tags: ["basics"],
  },
  {
    id: "ez-search-004",
    type: "mcq",
    track: "system-design",
    topic: "search",
    difficulty: 2,
    prompt: "Why does searching 'run' not find a document containing 'running'?",
    options: [
      { id: "a", text: "Without stemming they are indexed as two unrelated terms" },
      { id: "b", text: "The search index has not been rebuilt since that document" },
      { id: "c", text: "Partial matches need a wildcard to be enabled on the query" },
      { id: "d", text: "Relevance scoring ranked that document below the cut-off" },
    ],
    answer: "a",
    explanation:
      "Stemming reduces words to a common root so morphological variants match. Without it the index holds 'running' and the query asks for 'run', and they simply do not meet. The same analysis must run at index time and query time — a mismatch there finds nothing at all.",
    concepts: ["Stemming", "Text analysis", "Analyzer"],
    tags: ["analysis"],
  },
  {
    id: "ez-avail-001",
    type: "mcq",
    track: "system-design",
    topic: "availability",
    difficulty: 1,
    prompt: "What does 'three nines' mean?",
    options: [
      { id: "a", text: "99.9% available, which allows about nine hours down a year" },
      { id: "b", text: "Three independent copies of the service all running at once" },
      { id: "c", text: "Recovery within nine minutes of any failure being detected" },
      { id: "d", text: "Three regions, so two can fail without an outage occurring" },
    ],
    answer: "a",
    explanation:
      "The count of nines in the percentage. Useful anchors: three nines is hours a year, four nines is under an hour, five nines is minutes. Each extra nine cuts downtime tenfold and costs roughly an order of magnitude more engineering, which is why the claim deserves scrutiny.",
    concepts: ["Nines", "Availability", "Downtime budget"],
    tags: ["basics"],
  },
  {
    id: "ez-avail-002",
    type: "mcq",
    track: "system-design",
    topic: "availability",
    difficulty: 2,
    context: "A request must pass through two services in sequence, each independently 99.9% available.",
    prompt: "What is the availability of the pair in sequence?",
    options: [
      { id: "a", text: "About 99.8%, because availabilities multiply along a chain" },
      { id: "b", text: "99.9%, because the weakest link sets the overall number" },
      { id: "c", text: "About 99.99%, because either one can cover for the other" },
      { id: "d", text: "It cannot be calculated without knowing the failure causes" },
    ],
    answer: "a",
    explanation:
      "0.999 times 0.999 is 0.998. Every hard dependency you add makes you less available, which is how a chain of individually healthy services adds up to a number nobody is happy with. Redundancy buys nines back — but only where the copies fail independently.",
    concepts: ["Serial availability", "Hard dependency", "Nines"],
    tags: ["arithmetic"],
  },
];
