import type { Question } from "@/content/types";

/** Band 1 and 2 for the Code Craft and APIs & Integration lanes, to the lane
 *  bar of four. See easy-lanes-a.ts for why lanes sit at four where the spine
 *  sits at six. */
export const questions: Question[] = [
  {
    id: "ez-dpat-001",
    type: "mcq",
    track: "code-craft",
    topic: "design-patterns",
    difficulty: 1,
    prompt: "What is a design pattern?",
    options: [
      { id: "a", text: "A named solution to a problem that comes up again and again" },
      { id: "b", text: "A rule the language enforces about how classes may be built" },
      { id: "c", text: "A diagram showing how the parts of a system fit together" },
      { id: "d", text: "A template file that a framework generates new code from" },
    ],
    answer: "a",
    explanation:
      "The value is mostly the name. Saying 'that's a strategy' conveys the structure, the trade, and why it beats a growing if/else — in three words, to anybody who has the vocabulary. Patterns describe what people already do; they are not rules a language imposes.",
    concepts: ["Design pattern", "Shared vocabulary", "Strategy pattern"],
    tags: ["basics"],
  },
  {
    id: "ez-dpat-002",
    type: "mcq",
    track: "code-craft",
    topic: "design-patterns",
    difficulty: 2,
    prompt: "When does reaching for a pattern make code worse?",
    options: [
      { id: "a", text: "When it adds indirection for a variation that never arrives" },
      { id: "b", text: "When more than one developer will need to read the code later" },
      { id: "c", text: "When the language has no built-in support for that pattern" },
      { id: "d", text: "When the pattern was first published more than ten years ago" },
    ],
    answer: "a",
    explanation:
      "Every pattern buys flexibility along one axis and charges indirection for it. If that axis never varies you have paid and received nothing — a factory producing one type, a strategy with one implementation. The rule that survives contact: add the pattern at the second case, not the first.",
    concepts: ["Over-engineering", "YAGNI", "Accidental complexity"],
    tags: ["when-not-to"],
  },
  {
    id: "ez-dom-003",
    type: "mcq",
    track: "code-craft",
    topic: "domain-modelling",
    difficulty: 1,
    prompt: "What is a domain model?",
    options: [
      { id: "a", text: "Code shaped around the concepts the business actually talks about" },
      { id: "b", text: "A diagram of the tables and the relationships in a database" },
      { id: "c", text: "The set of API endpoints a service exposes to its callers" },
      { id: "d", text: "A description of which team owns each part of the system" },
    ],
    answer: "a",
    explanation:
      "The test is whether somebody who understands the business could read the type names and recognise their world. When the code says Order, Refund, and Shipment, a conversation with them is about the same things the code is about — which is where most requirements bugs stop happening.",
    concepts: ["Domain model", "Ubiquitous language", "Domain-driven design"],
    tags: ["basics"],
  },
  {
    id: "ez-dom-004",
    type: "mcq",
    track: "code-craft",
    topic: "domain-modelling",
    difficulty: 2,
    prompt: "What is the difference between an entity and a value object?",
    options: [
      { id: "a", text: "An entity has an identity that persists as its fields change" },
      { id: "b", text: "An entity is stored in a database and a value object is not" },
      { id: "c", text: "An entity can be changed and a value object is always frozen" },
      { id: "d", text: "An entity belongs to one service and a value object is shared" },
    ],
    answer: "a",
    explanation:
      "A person is the same person after changing address; five pounds is just five pounds, interchangeable with any other. That is the whole distinction, and it decides whether you compare by id or by contents — which in turn decides how equality, caching, and updates behave.",
    concepts: ["Entity", "Value object", "Identity versus equality"],
    tags: ["building-blocks"],
  },
  {
    id: "ez-spec-002",
    type: "mcq",
    track: "code-craft",
    topic: "spec-driven-development",
    difficulty: 2,
    prompt: "Why write acceptance criteria as examples rather than prose?",
    options: [
      { id: "a", text: "Two people can agree with a sentence and disagree about every case" },
      { id: "b", text: "Examples are quicker to write than a full description would be" },
      { id: "c", text: "Prose cannot later be turned into an automated test at all" },
      { id: "d", text: "Examples do not need to be reviewed by whoever requested it" },
    ],
    answer: "a",
    explanation:
      "'Search should handle typos' is something everyone nods at and nobody shares a meaning for. 'Searching recieve returns the receive results' is checkable, and the disagreement surfaces while it is still cheap. Examples also happen to be tests already written, which is a bonus rather than the point.",
    concepts: ["Acceptance criteria", "Specification by example", "Given-When-Then"],
    tags: ["examples"],
  },
  {
    id: "ez-flag-002",
    type: "mcq",
    track: "delivery",
    topic: "feature-flags",
    difficulty: 2,
    prompt: "What does a feature flag let you separate?",
    options: [
      { id: "a", text: "Shipping the code from turning the new behaviour on" },
      { id: "b", text: "Writing the feature from writing its automated tests" },
      { id: "c", text: "The frontend release cycle from the backend release cycle" },
      { id: "d", text: "Development environments from production environments" },
    ],
    answer: "a",
    explanation:
      "Deploy and release stop being the same event. The code can sit in production for a week, off, while you watch it do nothing — then go on for one percent of users without another deploy. It also means turning it off is a config change rather than a rollback.",
    concepts: ["Feature flag", "Deploy versus release", "Dark launch"],
    tags: ["basics"],
  },
  {
    id: "ez-cloud-001",
    type: "mcq",
    track: "delivery",
    topic: "cloud-deployment",
    difficulty: 1,
    prompt: "What does it mean for a server to be stateless?",
    options: [
      { id: "a", text: "It keeps nothing between requests that another instance would need" },
      { id: "b", text: "It stores no data at all, anywhere, at any point in time" },
      { id: "c", text: "It restarts automatically after every request it handles" },
      { id: "d", text: "It holds no configuration and reads everything from a file" },
    ],
    answer: "a",
    explanation:
      "State lives somewhere shared — a database, a cache, object storage — so any instance can serve any request. That is what makes horizontal scaling and rolling deploys possible: a request does not care which machine it lands on, and losing a machine loses nothing.",
    concepts: ["Stateless process", "Horizontal scaling", "Twelve-factor app"],
    tags: ["basics"],
  },
  {
    id: "ez-cloud-002",
    type: "mcq",
    track: "delivery",
    topic: "cloud-deployment",
    difficulty: 2,
    prompt: "Why does writing files to a container's local disk cause problems?",
    options: [
      { id: "a", text: "The disk goes away when the container does, and no other instance sees it" },
      { id: "b", text: "Container filesystems are much slower than network storage is" },
      { id: "c", text: "Containers are not permitted to write to their own disk at all" },
      { id: "d", text: "Writing to disk prevents the container from being restarted" },
    ],
    answer: "a",
    explanation:
      "Container filesystems are ephemeral and per-instance, so an upload written locally survives until the next deploy and is invisible to every other replica meanwhile. Uploads belong in object storage; anything you need to keep belongs somewhere the container's lifetime does not bound.",
    concepts: ["Ephemeral filesystem", "Object storage", "Twelve-factor app"],
    tags: ["state"],
  },
  {
    id: "ez-dep-001",
    type: "mcq",
    track: "delivery",
    topic: "dependencies",
    difficulty: 1,
    prompt: "What is a transitive dependency?",
    options: [
      { id: "a", text: "A package your dependencies depend on, that you never named" },
      { id: "b", text: "A package used only during the build, not while running" },
      { id: "c", text: "A package that is scheduled to be replaced by another one" },
      { id: "d", text: "A package that has to be installed globally, not per project" },
    ],
    answer: "a",
    explanation:
      "You choose a handful of packages and inherit hundreds. Most of what ends up in your application is code nobody on your team evaluated, which is why a vulnerability four levels down is still your vulnerability, and why what a package pulls in matters as much as what it does.",
    concepts: ["Transitive dependency", "Dependency tree", "Supply chain attack"],
    tags: ["basics"],
  },
  {
    id: "ez-dep-002",
    type: "mcq",
    track: "delivery",
    topic: "dependencies",
    difficulty: 2,
    prompt: "What does a lockfile give you?",
    options: [
      { id: "a", text: "The same resolved versions on every machine and every build" },
      { id: "b", text: "Protection against a dependency being removed from the registry" },
      { id: "c", text: "Automatic upgrades whenever a dependency publishes a patch" },
      { id: "d", text: "A list of which dependencies your code actually imports" },
    ],
    answer: "a",
    explanation:
      "Without one, a version range resolves to whatever is newest at install time, so two people a week apart get different code from identical files. The lockfile pins the whole resolved tree, which is what makes a build reproducible — and a bug reproducible with it.",
    concepts: ["Lockfile", "Reproducible build", "Semantic versioning"],
    tags: ["reproducibility"],
  },
  {
    id: "ez-rest-001",
    type: "mcq",
    track: "api-integration",
    topic: "rest-soap",
    difficulty: 2,
    prompt: "What makes an API RESTful rather than just HTTP?",
    options: [
      { id: "a", text: "It models nouns as resources and uses the methods for the verbs" },
      { id: "b", text: "It returns JSON rather than XML in every one of its responses" },
      { id: "c", text: "It is documented with OpenAPI and generates client libraries" },
      { id: "d", text: "It uses HTTPS and requires a token on every single request" },
    ],
    answer: "a",
    explanation:
      "Resources plus the uniform interface. /users/42 names a thing, and GET, PUT, and DELETE say what to do with it — which is what lets caches, proxies, and client libraries behave sensibly without knowing your API. JSON, OpenAPI, and TLS are all orthogonal to it.",
    concepts: ["REST", "Resource", "Uniform interface"],
    tags: ["basics"],
  },
  {
    id: "ez-contract-001",
    type: "mcq",
    track: "api-integration",
    topic: "api-contracts",
    difficulty: 1,
    prompt: "Why write the API contract before the implementation?",
    options: [
      { id: "a", text: "Both sides can build against it at once, and disagree early" },
      { id: "b", text: "It is required before the API can be deployed to production" },
      { id: "c", text: "Writing it afterwards takes considerably more time overall" },
      { id: "d", text: "The contract generates the server implementation for you" },
    ],
    answer: "a",
    explanation:
      "A contract agreed first is something the frontend can mock against on Monday while the backend builds the real one. The disagreement about what a field means then happens in a review rather than in integration testing, which is where it costs a week instead of an hour.",
    concepts: ["Spec-first development", "API contract", "Mock server"],
    tags: ["basics"],
  },
  {
    id: "ez-contract-002",
    type: "mcq",
    track: "api-integration",
    topic: "api-contracts",
    difficulty: 2,
    prompt: "What does validating requests against the schema at the boundary buy you?",
    options: [
      { id: "a", text: "Malformed input is rejected once, before any handler sees it" },
      { id: "b", text: "The database no longer needs its own constraints on the data" },
      { id: "c", text: "Clients receive a generated SDK matching the current schema" },
      { id: "d", text: "Responses are automatically kept in sync with the schema" },
    ],
    answer: "a",
    explanation:
      "One check at the edge, and everything past it can assume the shape is right — which removes a defensive branch from every handler. It does not remove the database's constraints: those protect against writers that never came through your API at all, such as a migration or a second service.",
    concepts: ["Schema validation", "Boundary validation", "Database constraint"],
    tags: ["validation"],
  },
  {
    id: "ez-hook-002",
    type: "mcq",
    track: "api-integration",
    topic: "webhooks",
    difficulty: 1,
    prompt: "What does a webhook save you doing?",
    options: [
      { id: "a", text: "Polling the other system repeatedly to ask whether anything changed" },
      { id: "b", text: "Authenticating each request that arrives from the other system" },
      { id: "c", text: "Storing your own copy of the other system's data locally" },
      { id: "d", text: "Handling the case where the other system is briefly unavailable" },
    ],
    answer: "a",
    explanation:
      "It inverts who calls whom. Instead of asking every thirty seconds whether a payment settled — mostly to be told no — you are told once, when it happens. What you take on in exchange is an endpoint that must be public, verified, and able to cope with duplicates.",
    concepts: ["Webhook", "Polling", "Event notification"],
    tags: ["basics"],
  },
  {
    id: "ez-hook-003",
    type: "mcq",
    track: "api-integration",
    topic: "webhooks",
    difficulty: 2,
    prompt: "Why must a webhook endpoint respond quickly?",
    options: [
      { id: "a", text: "The sender will time out and retry, producing a duplicate delivery" },
      { id: "b", text: "Senders rank endpoints by response time and throttle the slow ones" },
      { id: "c", text: "A slow response is treated as a signature verification failure" },
      { id: "d", text: "The connection cannot stay open longer than a few hundred milliseconds" },
    ],
    answer: "a",
    explanation:
      "Acknowledge first, process afterwards. If your handler does the work before responding, a slow downstream turns into a timeout at the sender, which retries — and now you are processing the same event twice while already behind. Take the payload, verify it, queue it, return 200.",
    concepts: ["Webhook timeout", "Asynchronous processing", "Idempotent consumer"],
    tags: ["handling"],
  },
  {
    id: "ez-auth-002",
    type: "mcq",
    track: "api-integration",
    topic: "api-auth",
    difficulty: 1,
    prompt: "What is the difference between an access token and a refresh token?",
    options: [
      { id: "a", text: "The access token is used on requests; the refresh token gets new ones" },
      { id: "b", text: "The access token is for users and the refresh token is for services" },
      { id: "c", text: "The access token is encrypted and the refresh token is signed" },
      { id: "d", text: "The access token is issued once and the refresh token every time" },
    ],
    answer: "a",
    explanation:
      "Short-lived and widely used, against long-lived and rarely used. The access token goes to every resource server, so it is kept brief to bound the damage if it leaks. The refresh token only ever goes back to the issuer, which can check it against a store and revoke it.",
    concepts: ["Access token", "Refresh token", "Token lifetime"],
    tags: ["tokens"],
  },
  {
    id: "ez-auth-003",
    type: "mcq",
    track: "api-integration",
    topic: "api-auth",
    difficulty: 2,
    prompt: "What does OAuth2 actually let a user do?",
    options: [
      { id: "a", text: "Grant an app limited access to their data without giving it a password" },
      { id: "b", text: "Sign in to several different sites using one set of credentials" },
      { id: "c", text: "Prove their own identity to an application that has asked for it" },
      { id: "d", text: "Encrypt whatever data an application stores on their behalf" },
    ],
    answer: "a",
    explanation:
      "Delegated authorisation, and delegated is the point: you let an application act on your behalf, within a scope, without ever handing it your password. Proving who you are is OpenID Connect, a layer on top — the two travel together and are not the same thing.",
    concepts: ["OAuth 2.0", "Delegated authorisation", "OpenID Connect", "Scope"],
    tags: ["oauth"],
  },
  {
    id: "ez-owasp-002",
    type: "mcq",
    track: "api-integration",
    topic: "api-owasp",
    difficulty: 1,
    prompt: "Why is checking a user's identity not enough on its own?",
    options: [
      { id: "a", text: "Knowing who they are does not say which records they may see" },
      { id: "b", text: "Identity checks can be bypassed by editing the request headers" },
      { id: "c", text: "The token proving identity may have expired since it was issued" },
      { id: "d", text: "Identity is checked by the gateway rather than the application" },
    ],
    answer: "a",
    explanation:
      "Authentication and authorisation are separate checks, and the second is the one that gets skipped. Being signed in as user 7 does not entitle you to invoice 91 — and an endpoint that verifies the token, then trusts the id in the URL, is the most exploited API flaw there is.",
    concepts: ["Broken Object Level Authorization", "Authorisation check", "IDOR"],
    tags: ["basics"],
  },
  {
    id: "ez-owasp-003",
    type: "mcq",
    track: "api-integration",
    topic: "api-owasp",
    difficulty: 2,
    prompt: "Why is returning extra fields the client does not display a problem?",
    options: [
      { id: "a", text: "The response is the API's real output, and anyone can read all of it" },
      { id: "b", text: "Extra fields make the response slower for the browser to parse" },
      { id: "c", text: "Clients may start depending on fields you meant to keep private" },
      { id: "d", text: "The schema no longer matches what the documentation promises" },
    ],
    answer: "a",
    explanation:
      "Hiding a field in the interface hides nothing: the network tab shows the whole response, and so does anyone calling the endpoint directly. This is excessive data exposure, and the fix is filtering on the server according to who is asking, not trusting the client to look away.",
    concepts: ["Excessive data exposure", "Response filtering", "Server-side authorisation"],
    tags: ["exposure"],
  },
  {
    id: "ez-gov-002",
    type: "mcq",
    track: "api-integration",
    topic: "api-governance",
    difficulty: 1,
    prompt: "Why does an API need a version at all?",
    options: [
      { id: "a", text: "So a change that breaks callers can ship without breaking them" },
      { id: "b", text: "So each release can be tracked against the team's own roadmap" },
      { id: "c", text: "So a client can tell which server instance answered its call" },
      { id: "d", text: "So the documentation stays matched to the code that is running" },
    ],
    answer: "a",
    explanation:
      "Versioning buys you the option to break something. Without it every change has to be compatible forever, and you either freeze or break people silently. With it you can run two shapes side by side for as long as callers need — a real cost, hence staying additive where you can.",
    concepts: ["API versioning", "Breaking change", "Backwards compatibility"],
    tags: ["basics"],
  },
  {
    id: "ez-gov-003",
    type: "mcq",
    track: "api-integration",
    topic: "api-governance",
    difficulty: 2,
    prompt: "What does deprecating an endpoint mean?",
    options: [
      { id: "a", text: "It still works, and a removal date has been announced for it" },
      { id: "b", text: "It has been removed and now returns an error to every caller" },
      { id: "c", text: "It is discouraged in the documentation but will never be removed" },
      { id: "d", text: "It works only for clients that were already using it before" },
    ],
    answer: "a",
    explanation:
      "Deprecated means still working, and going away — both halves matter. Announcing without a date produces an endpoint deprecated for six years that nobody dares remove; removing without announcing produces an outage in somebody else's system. The Sunset header carries the date to clients that read it.",
    concepts: ["Deprecation", "Sunset header", "Deprecation policy"],
    tags: ["lifecycle"],
  },
];
