import type { Question } from "@/content/types";

/** Band 1 and 2 for the Data & SQL, AI Engineering, and Enterprise lanes, to
 *  the lane bar of four. See easy-lanes-a.ts for why lanes sit at four where
 *  the spine sits at six. */
export const questions: Question[] = [
  {
    id: "ez-cte-002",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-subqueries",
    difficulty: 1,
    prompt: "What does WITH do at the start of a query?",
    options: [
      { id: "a", text: "Names a result you can then refer to like a table" },
      { id: "b", text: "Declares which tables the query is allowed to read" },
      { id: "c", text: "Sets options that apply for the rest of the session" },
      { id: "d", text: "Opens a transaction that the whole query runs inside" },
    ],
    answer: "a",
    explanation:
      "A common table expression names a step. The value is readability: a query built from three named stages reads top to bottom, where the same logic nested three deep has to be read inside out. It is still one query — nothing is stored.",
    concepts: ["Common table expression", "Query readability", "Subquery"],
    tags: ["basics"],
  },
  {
    id: "ez-cte-003",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-subqueries",
    difficulty: 2,
    prompt: "When is a subquery correlated?",
    options: [
      { id: "a", text: "When it references a column from the outer query's row" },
      { id: "b", text: "When it appears in the SELECT list rather than the FROM" },
      { id: "c", text: "When it returns more than a single row to the outer query" },
      { id: "d", text: "When it reads from the same table as the outer query does" },
    ],
    answer: "a",
    explanation:
      "It depends on the outer row, so it cannot be evaluated once — conceptually it runs per row. That is why a correlated subquery is fine on a hundred rows and a problem on a million, and why the usual rewrite is a join or a window function.",
    concepts: ["Correlated subquery", "Query plan", "Window function"],
    tags: ["correlation"],
  },
  {
    id: "ez-win-002",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-window-functions",
    difficulty: 1,
    prompt: "What does OVER () do after an aggregate?",
    options: [
      { id: "a", text: "Computes it across rows without collapsing them into one" },
      { id: "b", text: "Sorts the result by whichever column is being aggregated" },
      { id: "c", text: "Restricts the aggregate to only the rows matching a condition" },
      { id: "d", text: "Caches the aggregate so that repeated queries run faster" },
    ],
    answer: "a",
    explanation:
      "That is the whole difference from GROUP BY. SUM(x) collapses a group into one row; SUM(x) OVER () keeps every row and adds the total to each. It is what lets you show a row beside its share of the whole without joining the aggregate back.",
    concepts: ["Window function", "OVER clause", "GROUP BY"],
    tags: ["basics"],
  },
  {
    id: "ez-win-003",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-window-functions",
    difficulty: 2,
    prompt: "What do you use to compare a row with the one before it?",
    options: [
      { id: "a", text: "LAG, which reads a value from an earlier row in the order" },
      { id: "b", text: "A self join matching each row against its own predecessor" },
      { id: "c", text: "ORDER BY, which makes the previous row's value available" },
      { id: "d", text: "GROUP BY on the ordering column, then taking the minimum" },
    ],
    answer: "a",
    explanation:
      "LAG reaches backwards within the window's order, and LEAD forwards. Before window functions this needed a self join on row number, which was slow and easy to get subtly wrong — day-over-day change is the canonical case, and it is one line now.",
    concepts: ["LAG", "LEAD", "Window frame", "Self join"],
    tags: ["row-comparison"],
  },
  {
    id: "ez-sqlperf-002",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-performance",
    difficulty: 1,
    prompt: "What does EXPLAIN tell you?",
    options: [
      { id: "a", text: "The plan the database intends to use to answer the query" },
      { id: "b", text: "How long the query took the last time that it was executed" },
      { id: "c", text: "Which indexes are missing and therefore ought to be created" },
      { id: "d", text: "Whether the query returns the results that you expected" },
    ],
    answer: "a",
    explanation:
      "The plan, not the outcome: which indexes it will use, in what order it will join, and how many rows it expects at each step. Those expectations are the interesting part — when the estimate and reality diverge, the statistics are stale and the plan is built on fiction.",
    concepts: ["EXPLAIN", "Query planner", "Query plan"],
    tags: ["basics"],
  },
  {
    id: "ez-sqlperf-003",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-performance",
    difficulty: 2,
    prompt: "Why does an index on a column not help WHERE lower(email) = ?",
    options: [
      { id: "a", text: "The index holds the values, not the result of a function on them" },
      { id: "b", text: "Functions in a WHERE clause are always evaluated before indexes" },
      { id: "c", text: "Text columns cannot be indexed in a way that supports equality" },
      { id: "d", text: "The planner ignores indexes on any query using a comparison" },
    ],
    answer: "a",
    explanation:
      "An index stores email, and you are asking about lower(email) — a different set of values that was never indexed, so the engine scans. The cures are an expression index on lower(email), or storing the column already lowercased. Any transformation of the column side does this.",
    concepts: ["Sargable predicate", "Expression index", "Full table scan"],
    tags: ["indexes"],
  },
  {
    id: "ez-metric-002",
    type: "mcq",
    track: "sql-analytics",
    topic: "product-metrics",
    difficulty: 1,
    prompt: "What is a cohort?",
    options: [
      { id: "a", text: "A group of users defined by when they started, tracked over time" },
      { id: "b", text: "A group of users chosen at random to receive an experiment" },
      { id: "c", text: "The set of users who happened to be active on one day" },
      { id: "d", text: "The users who share a plan, a region, or a device type" },
    ],
    answer: "a",
    explanation:
      "Cohorts separate what changed from who joined. Overall retention can fall while every cohort improves, simply because a large new intake is younger — and only the cohort view shows that. The defining axis is time of joining, which is what makes them comparable.",
    concepts: ["Cohort analysis", "Retention", "Simpson's paradox"],
    tags: ["basics"],
  },
  {
    id: "ez-metric-003",
    type: "mcq",
    track: "sql-analytics",
    topic: "product-metrics",
    difficulty: 2,
    prompt: "What makes a metric actionable rather than vanity?",
    options: [
      { id: "a", text: "It can go down, and you would know what to do if it did" },
      { id: "b", text: "It is reported to the leadership team every single week" },
      { id: "c", text: "It is calculated from data the product already collects" },
      { id: "d", text: "It has gone up consistently over the last several quarters" },
    ],
    answer: "a",
    explanation:
      "Cumulative totals — signups ever, downloads ever — only rise, so they cannot tell you anything got worse. A metric earns its place by being able to deliver bad news, and by that bad news implying something. Growing every quarter is a property of the counter, not the product.",
    concepts: ["Vanity metric", "Actionable metric", "Cumulative total"],
    tags: ["quality"],
  },
  {
    id: "ez-stat-002",
    type: "mcq",
    track: "sql-analytics",
    topic: "statistics-basics",
    difficulty: 1,
    prompt: "Why is the median often better than the mean for latency?",
    options: [
      { id: "a", text: "One very slow request drags the mean and leaves the median alone" },
      { id: "b", text: "The median is quicker for a database to compute than the mean" },
      { id: "c", text: "The mean cannot be calculated at all when some values are missing" },
      { id: "d", text: "The median counts every request whereas the mean only samples" },
    ],
    answer: "a",
    explanation:
      "Latency distributions have a long right tail, and the mean is pulled towards it by a handful of outliers. The median says what a typical request experienced. Report both, plus p95 and p99 — the tail is where the unhappy users are, and invisible in either summary alone.",
    concepts: ["Median", "Right-skewed distribution", "Percentile"],
    tags: ["summaries"],
  },
  {
    id: "ez-stat-003",
    type: "mcq",
    track: "sql-analytics",
    topic: "statistics-basics",
    difficulty: 2,
    prompt: "Two things move together. What does that tell you?",
    options: [
      { id: "a", text: "Only that they move together — either may cause the other, or neither" },
      { id: "b", text: "That one causes the other, if the relationship is strong enough" },
      { id: "c", text: "That they share a cause, since coincidence is statistically unlikely" },
      { id: "d", text: "Nothing at all, because correlation is not a meaningful measure" },
    ],
    answer: "a",
    explanation:
      "Correlation is real evidence, and it underdetermines the explanation: A causes B, B causes A, something causes both, or it is chance. Ice cream sales and drownings rise together because of summer. Separating those four possibilities is what an experiment is for.",
    concepts: ["Correlation versus causation", "Confounding variable", "Reverse causation"],
    tags: ["inference"],
  },
  {
    id: "ez-ab-002",
    type: "mcq",
    track: "sql-analytics",
    topic: "ab-testing",
    difficulty: 1,
    prompt: "Why do both groups in an A/B test run at the same time?",
    options: [
      { id: "a", text: "So anything else that changes affects both groups equally" },
      { id: "b", text: "So the experiment finishes in half the time it would take" },
      { id: "c", text: "So each user can be shown both versions and then compared" },
      { id: "d", text: "So the results can be checked before the test has finished" },
    ],
    answer: "a",
    explanation:
      "Run them sequentially and you cannot separate your change from the week: a holiday, an outage, a marketing push. Running concurrently means every external factor lands on both groups, so the difference between them is attributable to the one thing you varied.",
    concepts: ["Control group", "Confounding variable", "Randomisation"],
    tags: ["basics"],
  },
  {
    id: "ez-ab-003",
    type: "mcq",
    track: "sql-analytics",
    topic: "ab-testing",
    difficulty: 2,
    prompt: "Why should you decide the sample size before starting?",
    options: [
      { id: "a", text: "Stopping when the result looks good makes false positives likely" },
      { id: "b", text: "The experiment platform requires a size before it will start" },
      { id: "c", text: "A larger sample always produces a more accurate conclusion" },
      { id: "d", text: "It determines how the users will be split between groups" },
    ],
    answer: "a",
    explanation:
      "Peek repeatedly and stop the moment p drops below 0.05 and you will cross that line eventually by chance alone — the 5% false positive rate applies to one look, not to twenty. Fixing the sample size in advance is what makes the number mean what it claims.",
    concepts: ["Peeking problem", "Optional stopping", "Statistical significance"],
    tags: ["design"],
  },
  {
    id: "ez-ml-001",
    type: "mcq",
    track: "ai-engineering",
    topic: "ml-basics",
    difficulty: 1,
    prompt: "What is a feature, in machine learning?",
    options: [
      { id: "a", text: "An individual input the model uses to make its prediction" },
      { id: "b", text: "A capability of the model that the users can see" },
      { id: "c", text: "A metric describing how well the model performs" },
      { id: "d", text: "A version of the model trained on more recent data" },
    ],
    answer: "a",
    explanation:
      "One column of the input. Choosing and shaping them — feature engineering — usually moves accuracy more than swapping the algorithm does, which is the opposite of where beginners spend their time. The other trap is a feature only knowable after the fact, which leaks the answer.",
    concepts: ["Feature", "Feature engineering", "Data leakage"],
    tags: ["basics"],
  },
  {
    id: "ez-llm-001",
    type: "mcq",
    track: "ai-engineering",
    topic: "llm-fundamentals",
    difficulty: 1,
    prompt: "What does a language model actually do?",
    options: [
      { id: "a", text: "Predicts the next token, repeatedly, given everything so far" },
      { id: "b", text: "Looks the answer up in the documents it was trained on" },
      { id: "c", text: "Runs a search over the web and summarises what it finds" },
      { id: "d", text: "Follows rules written by its authors for each request" },
    ],
    answer: "a",
    explanation:
      "Token by token, each one conditioned on everything before it. That single mechanism explains most of the behaviour worth knowing: why it is fluent about things it has no knowledge of, why the prompt matters so much, and why nothing is retrieved unless you retrieved it.",
    concepts: ["Token", "Next-token prediction", "Hallucination"],
    tags: ["basics"],
  },
  {
    id: "ez-llm-002",
    type: "mcq",
    track: "ai-engineering",
    topic: "llm-fundamentals",
    difficulty: 2,
    prompt: "What is in a model's context window?",
    options: [
      { id: "a", text: "Everything it can see this call — prompt, history, and retrieved text" },
      { id: "b", text: "The facts it learned during training, kept ready in memory" },
      { id: "c", text: "A record of the conversations it has had with this user before" },
      { id: "d", text: "The maximum length of the answer it is allowed to produce" },
    ],
    answer: "a",
    explanation:
      "Everything for this one call, and nothing carried over from the last — the model is stateless, and the appearance of memory is your application resending the history. That is also why a long conversation gets expensive: you pay for the whole transcript on every turn.",
    concepts: ["Context window", "Statelessness", "Token cost"],
    tags: ["context"],
  },
  {
    id: "ez-ai-002",
    type: "mcq",
    track: "ai-engineering",
    topic: "ai-systems",
    difficulty: 1,
    prompt: "What problem does retrieval-augmented generation solve?",
    options: [
      { id: "a", text: "The model answering from training data that may not contain it" },
      { id: "b", text: "The model being too slow to answer inside a single request" },
      { id: "c", text: "The model producing its output in an inconsistent format" },
      { id: "d", text: "The model costing too much to run for high-volume workloads" },
    ],
    answer: "a",
    explanation:
      "Fetch the relevant documents first, put them in the prompt, and ask the question against them. The model stops relying on what it happened to absorb in training, which is how you answer questions about your own data — and why a wrong answer is usually a retrieval failure.",
    concepts: ["Retrieval-augmented generation", "Grounding", "Retrieval recall"],
    tags: ["rag"],
  },
  {
    id: "ez-ai-003",
    type: "mcq",
    track: "ai-engineering",
    topic: "ai-systems",
    difficulty: 2,
    prompt: "Why is a document split into chunks before being embedded?",
    options: [
      { id: "a", text: "An embedding of a whole document blurs everything it contains" },
      { id: "b", text: "Embedding models cannot process more than a few words at once" },
      { id: "c", text: "Chunks are cheaper to store than the full document would be" },
      { id: "d", text: "The vector index requires every entry to be the same length" },
    ],
    answer: "a",
    explanation:
      "An embedding is one point for the whole input, so a fifty-page document becomes a single average of everything it says — close to nothing in particular. Chunking keeps each vector about one idea. Too small and you lose the context that made it meaningful, which is the tuning problem.",
    concepts: ["Chunking", "Embedding", "Context dilution"],
    tags: ["retrieval"],
  },
  {
    id: "ez-agent-002",
    type: "mcq",
    track: "ai-engineering",
    topic: "agents-tools",
    difficulty: 1,
    prompt: "What is a tool, to an AI agent?",
    options: [
      { id: "a", text: "A function it can call, described so the model knows when to" },
      { id: "b", text: "A prompt template that is stored for reuse across conversations" },
      { id: "c", text: "A rule constraining what the agent is permitted to answer" },
      { id: "d", text: "A second model that is consulted when the first one is unsure" },
    ],
    answer: "a",
    explanation:
      "A function plus a description, and the description does most of the work — it is read by the model, so 'when to use this' earns more than any amount of parameter detail. The model chooses; your runtime validates the arguments and actually runs it.",
    concepts: ["Tool use", "Function calling", "Tool description"],
    tags: ["basics"],
  },
  {
    id: "ez-agent-003",
    type: "mcq",
    track: "ai-engineering",
    topic: "agents-tools",
    difficulty: 2,
    prompt: "Why does an agent loop need a limit on iterations?",
    options: [
      { id: "a", text: "Nothing else stops it retrying a failing step indefinitely" },
      { id: "b", text: "Models become less accurate the longer a conversation runs" },
      { id: "c", text: "Each iteration must complete inside the HTTP request timeout" },
      { id: "d", text: "Tools cannot be called more than a fixed number of times" },
    ],
    answer: "a",
    explanation:
      "The loop ends when the model decides to answer, and nothing guarantees it will. A tool that keeps failing produces a model that keeps trying, and every turn costs tokens and time. Cap the iterations, cap the spend, and give it a way to give up and say so.",
    concepts: ["Agent loop", "Iteration limit", "Human in the loop"],
    tags: ["loops"],
  },
  {
    id: "ez-mcp-001",
    type: "mcq",
    track: "ai-engineering",
    topic: "mcp-servers",
    difficulty: 1,
    prompt: "What does the Model Context Protocol standardise?",
    options: [
      { id: "a", text: "How a model is given access to tools and data by a server" },
      { id: "b", text: "How prompts ought to be written for the best model results" },
      { id: "c", text: "How a model is packaged and then deployed onto a platform" },
      { id: "d", text: "How the output of a model is validated against a schema" },
    ],
    answer: "a",
    explanation:
      "One protocol instead of a bespoke integration per client. A server exposes tools, resources, and prompts; any compatible client can use them. The value is the same as any interface standard — the integrations become a small number rather than clients times services.",
    concepts: ["Model Context Protocol", "Integration standard", "Tool use"],
    tags: ["basics"],
  },
  {
    id: "ez-mcp-002",
    type: "mcq",
    track: "ai-engineering",
    topic: "mcp-servers",
    difficulty: 2,
    prompt: "Why should an MCP server expose few, task-shaped tools?",
    options: [
      { id: "a", text: "Every tool description costs context, and more choices means worse choices" },
      { id: "b", text: "Servers are limited in how many tools they may register" },
      { id: "c", text: "Each tool must be approved by the client before it is used" },
      { id: "d", text: "Fewer tools means there is less code for the server to maintain" },
    ],
    answer: "a",
    explanation:
      "The tool list is part of the prompt. Wrapping every endpoint one-to-one fills the window with options and asks the model to do the integration work in its head. Model one task per tool — 'create an invoice', not four calls the caller has to sequence correctly.",
    concepts: ["Tool design", "Task-oriented API", "Context window"],
    tags: ["design"],
  },
  {
    id: "ez-vibe-002",
    type: "mcq",
    track: "ai-engineering",
    topic: "ai-assisted-coding",
    difficulty: 1,
    prompt: "What is the biggest risk in accepting generated code you have not read?",
    options: [
      { id: "a", text: "You cannot maintain or debug something you never understood" },
      { id: "b", text: "The generated code will use libraries you have not installed" },
      { id: "c", text: "The code will not match the formatting rules of the project" },
      { id: "d", text: "The tool may have produced the same code for somebody else" },
    ],
    answer: "a",
    explanation:
      "It is yours once you merge it, and it will break at a time you did not choose. Formatting is a linter's problem and a missing import fails loudly. The quiet failure is code that works today and is unmaintainable the moment it stops, because nobody can explain it.",
    concepts: ["Code ownership", "Maintainability", "Code review"],
    tags: ["basics"],
  },
  {
    id: "ez-vsec-002",
    type: "mcq",
    track: "ai-engineering",
    topic: "ai-coding-security",
    difficulty: 1,
    prompt: "Why check that a package an AI tool suggests actually exists?",
    options: [
      { id: "a", text: "Models invent plausible names, and attackers register them" },
      { id: "b", text: "Suggested packages are often out of date by several versions" },
      { id: "c", text: "The package may not be compatible with your runtime version" },
      { id: "d", text: "Licence terms may prevent you using it in a commercial product" },
    ],
    answer: "a",
    explanation:
      "A model asked for a library will sometimes produce a name that sounds right and does not exist. Attackers watch for the ones that recur and register them, so the install succeeds and runs their code. Check the package is real, and is the one you meant, before installing.",
    concepts: ["Package hallucination", "Slopsquatting", "Supply chain attack"],
    tags: ["packages"],
  },
  {
    id: "ez-vsec-003",
    type: "mcq",
    track: "ai-engineering",
    topic: "ai-coding-security",
    difficulty: 2,
    prompt: "Why does generated code often contain insecure patterns?",
    options: [
      { id: "a", text: "It reflects what is common in its training data, tutorials included" },
      { id: "b", text: "Models deliberately favour brevity over safety in their output" },
      { id: "c", text: "Security fixes are usually published after a model is trained" },
      { id: "d", text: "Generated code skips the validation that a developer would write" },
    ],
    answer: "a",
    explanation:
      "Tutorials disable TLS verification to get past a certificate error, use a permissive CORS header to make an example work, and build SQL by concatenation because it reads more clearly. All of that is in the training data, so it comes back out — most often in those three places.",
    concepts: ["Insecure defaults", "Permissive CORS", "SQL injection", "Training data bias"],
    tags: ["patterns"],
  },
  {
    id: "ez-eid-002",
    type: "mcq",
    track: "data-enterprise",
    topic: "enterprise-identity",
    difficulty: 1,
    prompt: "What is an identity provider?",
    options: [
      { id: "a", text: "The system that authenticates users on behalf of other applications" },
      { id: "b", text: "The directory listing which employees work at the organisation" },
      { id: "c", text: "The service that issues API keys out to third-party developers" },
      { id: "d", text: "The component that decides which permissions a role carries" },
    ],
    answer: "a",
    explanation:
      "One place holds the credentials and vouches for the user to everybody else. That is what makes single sign-on work, and it is also why the security question moves: your application never sees a password, and instead has to validate an assertion properly.",
    concepts: ["Identity provider", "Single sign-on", "Service provider"],
    tags: ["basics"],
  },
  {
    id: "ez-eid-003",
    type: "mcq",
    track: "data-enterprise",
    topic: "enterprise-identity",
    difficulty: 2,
    prompt: "Why do enterprises care so much about deprovisioning?",
    options: [
      { id: "a", text: "An account that outlives the employee is an unmonitored way in" },
      { id: "b", text: "Unused accounts continue to be charged for under the licence" },
      { id: "c", text: "Directories slow down as the number of accounts increases" },
      { id: "d", text: "Auditors require the total account count to match headcount" },
    ],
    answer: "a",
    explanation:
      "Onboarding is visible and gets done; offboarding is invisible and does not. An account nobody uses is an account nobody watches, and it keeps whatever access it had on the day the person left. SCIM exists so the directory pushes the removal rather than hoping somebody remembers.",
    concepts: ["Deprovisioning", "SCIM", "Orphaned account"],
    tags: ["lifecycle"],
  },
  {
    id: "ez-eint-002",
    type: "mcq",
    track: "data-enterprise",
    topic: "enterprise-integration",
    difficulty: 1,
    prompt: "What is ETL?",
    options: [
      { id: "a", text: "Extracting data from systems, reshaping it, and loading it elsewhere" },
      { id: "b", text: "A protocol two enterprise systems use to exchange messages" },
      { id: "c", text: "A pattern for keeping two databases continuously in step" },
      { id: "d", text: "A standard describing how business events should be named" },
    ],
    answer: "a",
    explanation:
      "Extract, transform, load — moving data out of the systems that run the business and into somewhere it can be analysed. Modern platforms often reorder it to ELT, loading raw and transforming in the warehouse, because storage got cheap and the raw copy is worth keeping.",
    concepts: ["ETL", "ELT", "Data warehouse"],
    tags: ["basics"],
  },
  {
    id: "ez-eint-003",
    type: "mcq",
    track: "data-enterprise",
    topic: "enterprise-integration",
    difficulty: 2,
    prompt: "Why analyse data on a separate database from the one serving the app?",
    options: [
      { id: "a", text: "A heavy analytical query would compete with live traffic for resources" },
      { id: "b", text: "Analytical tools cannot connect to a production database directly" },
      { id: "c", text: "The production database cannot store more than a year of history" },
      { id: "d", text: "Analysts are not permitted access to production systems at all" },
    ],
    answer: "a",
    explanation:
      "A query scanning two years of orders and one paying for a checkout compete for the same buffer cache and the same connections. Separating them also lets each be shaped for its job: rows for transactions, columns for aggregates over millions of them.",
    concepts: ["OLTP", "OLAP", "Data warehouse", "Read replica"],
    tags: ["separation"],
  },
  {
    id: "ez-tenant-002",
    type: "mcq",
    track: "data-enterprise",
    topic: "multi-tenancy",
    difficulty: 1,
    prompt: "What is a tenant?",
    options: [
      { id: "a", text: "One customer organisation whose data has to stay separate" },
      { id: "b", text: "One running instance of the application on a given server" },
      { id: "c", text: "One individual user account inside a customer organisation" },
      { id: "d", text: "One database schema that holds a subset of all the data" },
    ],
    answer: "a",
    explanation:
      "The unit of isolation, and it is an organisation rather than a person — a tenant has many users, and the boundary that must not leak is the one between tenants. Getting that wrong at the data layer is how one customer ends up seeing another's records.",
    concepts: ["Multi-tenancy", "Tenant isolation", "Tenant identifier"],
    tags: ["basics"],
  },
  {
    id: "ez-tenant-003",
    type: "mcq",
    track: "data-enterprise",
    topic: "multi-tenancy",
    difficulty: 2,
    prompt: "What is the main risk of a shared-schema multi-tenant database?",
    options: [
      { id: "a", text: "One forgotten WHERE clause exposes every other tenant's rows" },
      { id: "b", text: "Tenants compete for the same disk and so queries run slower" },
      { id: "c", text: "A schema change has to be applied to each tenant separately" },
      { id: "d", text: "Each tenant needs its own connection pool to the database" },
    ],
    answer: "a",
    explanation:
      "Isolation depends on every query remembering the tenant filter, which is a discipline rather than a guarantee. Row-level security moves it into the database, so a query without the filter returns nothing rather than everything — the difference between a convention and an enforcement.",
    concepts: ["Shared schema multi-tenancy", "Row-level security", "Tenant isolation"],
    tags: ["isolation"],
  },
  {
    id: "ez-priv-002",
    type: "mcq",
    track: "data-enterprise",
    topic: "data-privacy",
    difficulty: 1,
    prompt: "What does data minimisation mean?",
    options: [
      { id: "a", text: "Collecting only what you need, and keeping it only as long" },
      { id: "b", text: "Compressing the data you store so it occupies less space" },
      { id: "c", text: "Removing duplicate records so that each person appears once" },
      { id: "d", text: "Restricting who inside the company can read personal data" },
    ],
    answer: "a",
    explanation:
      "The most effective privacy control, because data you never collected cannot leak, be subpoenaed, or need deleting. It is also the cheapest: every field you decline to store is one you do not have to secure, audit, retain, or explain. Access control is a separate and later question.",
    concepts: ["Data minimisation", "Data retention", "Personally identifiable information"],
    tags: ["basics"],
  },
  {
    id: "ez-priv-003",
    type: "mcq",
    track: "data-enterprise",
    topic: "data-privacy",
    difficulty: 2,
    prompt: "Why is deleting a user's row often not enough?",
    options: [
      { id: "a", text: "Copies live on in backups, logs, analytics, and third parties" },
      { id: "b", text: "The row is only marked deleted and remains readable in place" },
      { id: "c", text: "Databases keep a deleted row until the table is next vacuumed" },
      { id: "d", text: "Foreign keys prevent the row from being removed while referenced" },
    ],
    answer: "a",
    explanation:
      "Personal data spreads. It is in last month's backup, in the log line that recorded the request, in the warehouse export, and at whichever vendor you sent it to — none of which a single DELETE touches. Knowing where it went is what makes erasure possible at all.",
    concepts: ["Right to erasure", "Data inventory", "Data processor"],
    tags: ["erasure"],
  },
];
