import type { Question } from "@/content/types";

/** Band 1 and 2 for system design, AI engineering, API, and data topics that
 *  were authored mid-to-advanced. A learner whose accuracy drops bands to
 *  [1,2] and needs a real pool there, not the same mid-tier questions. */
export const questions: Question[] = [
  // ============================ System Design =============================
  {
    id: "ez-cdn-001",
    type: "mcq",
    track: "system-design",
    topic: "cdn",
    difficulty: 1,
    prompt: "What does a CDN do?",
    options: [
      { id: "a", text: "Caches content on servers physically closer to users" },
      { id: "b", text: "Compresses files so they transfer faster" },
      { id: "c", text: "Distributes database writes across regions" },
      { id: "d", text: "Encrypts traffic between browser and origin" },
    ],
    answer: "a",
    explanation:
      "The win is distance. A user in Sydney fetching from a Sydney edge saves the round trip to Virginia, which no amount of compression can recover. Compression and TLS are separate concerns that happen to be handled at the same layer.",
    concepts: ["Content delivery network", "Edge cache", "Round-trip time"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-cdn-002",
    type: "mcq",
    track: "system-design",
    topic: "cdn",
    difficulty: 2,
    context: "A CSS file is updated but users keep seeing the old version.",
    prompt:
      "Why do users keep seeing an old CSS file after it has been updated?",
    options: [
      { id: "a", text: "A cached copy has not expired yet at the edge or in the browser" },
      { id: "b", text: "The CDN failed to receive the deploy" },
      { id: "c", text: "The file was uploaded to the wrong region" },
      { id: "d", text: "The browser does not support the new syntax" },
    ],
    answer: "a",
    explanation:
      "Caches serve what they hold until it expires. This is exactly why build tools put a hash in the filename — new content gets a new URL, so there is nothing stale to serve and no purge to wait for.",
    concepts: ["Cache expiry", "Cache busting", "Content-addressed URL"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-shard-001",
    type: "mcq",
    track: "system-design",
    topic: "sharding",
    difficulty: 1,
    prompt: "What is sharding?",
    options: [
      { id: "a", text: "Splitting one dataset across several machines" },
      { id: "b", text: "Keeping copies of the same data on several machines" },
      { id: "c", text: "Compressing data to fit on fewer machines" },
      { id: "d", text: "Backing data up to a second location" },
    ],
    answer: "a",
    explanation:
      "Sharding splits, replication copies. They solve different problems and are often used together: shards divide the data so it fits and keeps up, replicas of each shard give durability and read capacity.",
    concepts: ["Sharding", "Partitioning", "Replication"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-shard-002",
    type: "mcq",
    track: "system-design",
    topic: "sharding",
    difficulty: 2,
    prompt: "Why is choosing a shard key such a consequential decision?",
    options: [
      {
        id: "a",
        text: "It decides where every row lives, and changing it means moving all the data",
      },
      { id: "b", text: "It determines which database engine you can use" },
      { id: "c", text: "It sets the maximum number of rows per table" },
      { id: "d", text: "It cannot be indexed once chosen" },
    ],
    answer: "a",
    explanation:
      "The key is the routing rule for the whole dataset, so changing it is a migration of everything while serving traffic. That is why it is worth spending real time on before you shard, and why the honest advice is not to shard until you must.",
    concepts: ["Shard key", "Data migration", "Resharding"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-repl-001",
    type: "mcq",
    track: "system-design",
    topic: "replication",
    difficulty: 2,
    prompt: "In leader-follower replication, where do writes go?",
    options: [
      { id: "a", text: "Only to the leader, which then propagates them to followers" },
      { id: "b", text: "To any node, which then syncs with the others" },
      { id: "c", text: "To all nodes simultaneously" },
      { id: "d", text: "To followers, which forward them to the leader" },
    ],
    answer: "a",
    explanation:
      "One writer means no write conflicts to resolve, which is what makes this the simplest and most common arrangement. Followers serve reads, and the gap before they catch up is replication lag.",
    concepts: ["Leader-follower replication", "Replication lag", "Read replica"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-cons-001",
    type: "mcq",
    track: "system-design",
    topic: "consistency",
    difficulty: 1,
    prompt: "What does eventual consistency mean?",
    options: [
      {
        id: "a",
        text: "If writes stop, all replicas will converge on the same value in time",
      },
      { id: "b", text: "Every read always returns the latest write" },
      { id: "c", text: "Data is consistent only during business hours" },
      { id: "d", text: "Writes eventually succeed even if they fail at first" },
    ],
    answer: "a",
    explanation:
      "It promises convergence and says nothing about when. That is often perfectly fine — nobody notices a like count being briefly stale — and completely unacceptable for a balance.",
    concepts: ["Eventual consistency", "Strong consistency", "Replica convergence"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-cons-002",
    type: "mcq",
    track: "system-design",
    topic: "consistency",
    difficulty: 2,
    prompt: "Why does strong consistency cost more than eventual consistency?",
    options: [
      { id: "a", text: "Nodes must coordinate before answering, which costs round trips" },
      { id: "b", text: "It requires more disk storage per replica" },
      { id: "c", text: "It prevents the use of read replicas entirely" },
      { id: "d", text: "It needs a larger number of nodes" },
    ],
    answer: "a",
    explanation:
      "Guaranteeing you see the latest write means checking with whoever might hold it, and that check is network latency you pay on every operation. Eventual consistency skips the coordination, which is exactly why it is faster and why it can be stale.",
    concepts: ["Strong consistency", "Coordination cost", "Latency"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-ms-001",
    type: "mcq",
    track: "system-design",
    topic: "microservices",
    difficulty: 1,
    prompt: "What does splitting an application into services buy you?",
    options: [
      {
        id: "a",
        text: "Independent deployment and scaling, at the cost of network calls and distributed failure",
      },
      { id: "b", text: "Faster code, because each service is smaller" },
      { id: "c", text: "Fewer bugs, because the code is separated" },
      { id: "d", text: "Lower infrastructure cost" },
    ],
    answer: "a",
    explanation:
      "The gains are organisational and operational: teams ship on their own schedule and scale the hot part alone. The costs are real — a function call becomes a network call that can be slow, fail, or half-succeed.",
    concepts: ["Microservices", "Independent deployment", "Distributed failure"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-ms-002",
    type: "mcq",
    track: "system-design",
    topic: "microservices",
    difficulty: 2,
    prompt: "Why does every call to another service need a timeout?",
    options: [
      {
        id: "a",
        text: "Without one, a slow dependency ties up your threads until your service fails too",
      },
      { id: "b", text: "Timeouts make the remote service respond faster" },
      { id: "c", text: "The network requires them to route correctly" },
      { id: "d", text: "They prevent the request from being retried" },
    ],
    answer: "a",
    explanation:
      "A call with no timeout can wait indefinitely while holding a thread and a connection. Enough of those and you have no capacity left, so your service dies of someone else's problem. A timeout converts their outage into your degraded response.",
    concepts: ["Timeout", "Thread pool exhaustion", "Cascading failure"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-search-001",
    type: "mcq",
    track: "system-design",
    topic: "search",
    difficulty: 1,
    prompt: "Why do applications use a dedicated search index instead of querying the database with LIKE?",
    options: [
      {
        id: "a",
        text: "A search index is built for matching text quickly and ranking by relevance",
      },
      { id: "b", text: "Databases cannot store text longer than a few hundred characters" },
      { id: "c", text: "LIKE queries are not supported by most databases" },
      { id: "d", text: "Search indexes use less storage than a database" },
    ],
    answer: "a",
    explanation:
      "A substring LIKE cannot use an ordinary index, so it scans, and it has no notion of which result is better. A search index inverts the problem — term to documents — and scores results, which is the part a database has no opinion about.",
    concepts: ["Inverted index", "Full-text search", "Relevance ranking"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-search-002",
    type: "mcq",
    track: "system-design",
    topic: "search",
    difficulty: 2,
    prompt: "A search index is a copy of data that lives in your database. What does that imply?",
    options: [
      { id: "a", text: "It needs an update path, and it will drift out of sync" },
      { id: "b", text: "The database becomes read-only" },
      { id: "c", text: "Search results are always older than a day" },
      { id: "d", text: "The database no longer needs indexes" },
    ],
    answer: "a",
    explanation:
      "Any denormalised copy carries a synchronisation obligation. Deciding how updates reach the index — and what happens when one fails — is the actual engineering work; standing up the index is the easy part.",
    concepts: ["Denormalisation", "Index synchronisation", "Change data capture"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-obs-001",
    type: "mcq",
    track: "system-design",
    topic: "observability",
    difficulty: 1,
    prompt: "What is the difference between logs and metrics?",
    options: [
      {
        id: "a",
        text: "Logs record individual events in detail; metrics are cheap aggregates over many",
      },
      { id: "b", text: "Logs are for errors and metrics are for successes" },
      { id: "c", text: "Logs are stored on disk and metrics in memory" },
      { id: "d", text: "They are the same data at different retention periods" },
    ],
    answer: "a",
    explanation:
      "Metrics answer \"how is the system doing\" cheaply and cannot tell you about one specific request. Logs answer \"what happened to this request\" and get expensive at volume. Traces are the third leg, following one request across services.",
    concepts: ["Logs", "Metrics", "Distributed tracing"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-bp-001",
    type: "mcq",
    track: "system-design",
    topic: "backpressure",
    difficulty: 2,
    prompt: "What is back pressure?",
    options: [
      {
        id: "a",
        text: "A system signalling callers to slow down rather than accepting work it cannot do",
      },
      { id: "b", text: "The load a database places on its disks" },
      { id: "c", text: "Retrying failed requests until they succeed" },
      { id: "d", text: "Latency caused by network congestion" },
    ],
    answer: "a",
    explanation:
      "Accepting everything and queueing it forever does not absorb overload, it hides it — until latency and memory make everything fail at once. Refusing work honestly lets callers back off and lets the system recover.",
    concepts: ["Back pressure", "Load shedding", "Bounded queue"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-arch-001",
    type: "mcq",
    track: "system-design",
    topic: "arch-patterns",
    difficulty: 2,
    prompt: "What problem does an anti-corruption layer solve?",
    options: [
      {
        id: "a",
        text: "It translates an external system's model into yours, so their design does not leak into your code",
      },
      { id: "b", text: "It validates that incoming data is not malicious" },
      { id: "c", text: "It encrypts data exchanged with third parties" },
      { id: "d", text: "It prevents database corruption during writes" },
    ],
    answer: "a",
    explanation:
      "Despite the name it is about design, not security. Without one, a legacy or vendor model spreads through your codebase and their next breaking change reaches everywhere. With one, it stops at a translation boundary.",
    concepts: ["Anti-corruption layer", "Bounded context", "Adapter pattern"],
    tags: ["fundamentals"],
  },

  // ============================ AI Engineering ============================
  {
    id: "ez-ai-001",
    type: "mcq",
    track: "ai-engineering",
    topic: "ai-systems",
    difficulty: 2,
    prompt: "In a RAG system, what is an embedding?",
    options: [
      {
        id: "a",
        text: "A numeric vector representing text, so similar meanings sit close together",
      },
      { id: "b", text: "A compressed copy of the document" },
      { id: "c", text: "The prompt template sent to the model" },
      { id: "d", text: "A summary of the document generated by the model" },
    ],
    answer: "a",
    explanation:
      "Turning text into vectors is what makes similarity searchable: find the vectors nearest the query and you have found related passages, even when they share no words. That last part is also why embeddings are poor at exact identifiers.",
    concepts: ["Embedding", "Vector similarity", "Semantic search"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-agent-001",
    type: "mcq",
    track: "ai-engineering",
    topic: "agents-tools",
    difficulty: 2,
    prompt: "How does a model decide which tool to call?",
    options: [
      { id: "a", text: "From the tool's name, description, and parameter schema" },
      { id: "b", text: "By trying each tool until one succeeds" },
      { id: "c", text: "From the order the tools were registered in" },
      { id: "d", text: "By asking the user to choose" },
    ],
    answer: "a",
    explanation:
      "The description is the interface. That makes a vague one a genuine bug rather than a documentation gap — wrong tool choices usually trace back to descriptions that do not say when *not* to use the tool.",
    concepts: ["Tool description", "Function calling", "Tool selection"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-vibe-001",
    type: "mcq",
    track: "ai-engineering",
    topic: "ai-assisted-coding",
    difficulty: 2,
    prompt: "Why review a small generated diff rather than a large one?",
    options: [
      {
        id: "a",
        text: "Attention does not scale with size — a large diff gets skimmed and approved",
      },
      { id: "b", text: "Large diffs are more likely to have merge conflicts" },
      { id: "c", text: "Small diffs generate faster" },
      { id: "d", text: "Large diffs cannot be reverted" },
    ],
    answer: "a",
    explanation:
      "The same effect that makes big pull requests get rubber-stamped applies here, and it bites harder because the code arrives faster than you can read it. Forty lines you actually read beats eight hundred you scroll past.",
    concepts: ["Code review", "Pull request size", "Incremental development"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-vsec-001",
    type: "mcq",
    track: "ai-engineering",
    topic: "ai-coding-security",
    difficulty: 2,
    context: "You paste a stack trace containing a live API key into an AI tool.",
    prompt: "What should you do after pasting a live API key into an AI tool?",
    options: [
      { id: "a", text: "Rotate the key — it must be treated as compromised" },
      { id: "b", text: "Delete the conversation" },
      { id: "c", text: "Nothing, if the tool promises not to train on your data" },
      { id: "d", text: "Change the key's permissions to read-only" },
    ],
    answer: "a",
    explanation:
      "Once a secret leaves your control you cannot un-send it, and deleting a conversation does not undo transmission. Rotation is the only action that restores the property you care about. Redacting before pasting prevents it entirely.",
    concepts: ["Secret rotation", "Data leakage", "Redaction"],
    tags: ["fundamentals"],
  },

  // ========================== API & Integration ===========================
  {
    id: "ez-hook-001",
    type: "mcq",
    track: "api-integration",
    topic: "webhooks",
    difficulty: 2,
    prompt: "Why must a webhook receiver verify the request signature?",
    options: [
      {
        id: "a",
        text: "The endpoint is public, so anyone could send it a convincing-looking payload",
      },
      { id: "b", text: "Signatures compress the payload" },
      { id: "c", text: "Providers reject unsigned responses" },
      { id: "d", text: "It confirms the payload is valid JSON" },
    ],
    answer: "a",
    explanation:
      "Without verification, anyone who learns your URL can tell you an order was paid. The signature proves the sender holds the shared secret, and it must be checked before you act on anything in the payload.",
    concepts: ["HMAC signature", "Webhook verification", "Shared secret"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-auth-001",
    type: "mcq",
    track: "api-integration",
    topic: "api-auth",
    difficulty: 2,
    prompt: "What is an access token?",
    options: [
      {
        id: "a",
        text: "A short-lived credential proving the bearer may perform certain actions",
      },
      { id: "b", text: "A permanent identifier for a user account" },
      { id: "c", text: "An encrypted copy of the user's password" },
      { id: "d", text: "A session cookie set by the browser" },
    ],
    answer: "a",
    explanation:
      "It is a bearer credential: whoever holds it can use it, which is why it belongs over TLS, out of URLs, and out of logs. Keeping it short-lived bounds the damage if it does leak, with a refresh token handling renewal.",
    concepts: ["Access token", "Bearer token", "Refresh token"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-owasp-001",
    type: "mcq",
    track: "api-integration",
    topic: "api-owasp",
    difficulty: 2,
    prompt: "Why is hiding a field in the UI not a way to protect it?",
    options: [
      {
        id: "a",
        text: "The data is still in the API response, which anyone can read directly",
      },
      { id: "b", text: "Hidden fields are still rendered to the page" },
      { id: "c", text: "The browser caches hidden fields" },
      { id: "d", text: "It only works when JavaScript is enabled" },
    ],
    answer: "a",
    explanation:
      "The UI is one client among many. Open developer tools or call the endpoint with curl and the field is right there. Filtering has to happen on the server, shaped by what the caller is entitled to see.",
    concepts: ["Excessive data exposure", "Client-side filtering", "Server-side authorisation"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-gov-001",
    type: "mcq",
    track: "api-integration",
    topic: "api-governance",
    difficulty: 2,
    prompt: "What makes a change to a public API 'breaking'?",
    options: [
      { id: "a", text: "An existing client that worked before stops working" },
      { id: "b", text: "The change is large" },
      { id: "c", text: "It requires a database migration" },
      { id: "d", text: "It changes response times" },
    ],
    answer: "a",
    explanation:
      "Size is irrelevant — renaming one field is breaking, adding fifty optional ones is not. The test is always whether a caller you do not control, doing what they did yesterday, still works today.",
    concepts: ["Breaking change", "Backwards compatibility", "API contract"],
    tags: ["fundamentals"],
  },

  // =========================== Data & Enterprise ==========================
  {
    id: "ez-mig-001",
    type: "mcq",
    track: "data-enterprise",
    topic: "migrations",
    difficulty: 2,
    prompt: "Why is dropping a column riskier than adding one?",
    options: [
      {
        id: "a",
        text: "Code still running may read it, and the data cannot be recovered afterwards",
      },
      { id: "b", text: "Dropping a column locks the table for longer" },
      { id: "c", text: "Adding a column requires no migration" },
      { id: "d", text: "Dropped columns break the primary key" },
    ],
    answer: "a",
    explanation:
      "Additive changes are invisible to code that does not know about them. Removals are the opposite: any instance still running the previous deploy breaks, and unlike most deploys you cannot simply roll back, because the data is gone.",
    concepts: ["Expand and contract", "Destructive migration", "Rollback"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-dbsec-001",
    type: "mcq",
    track: "data-enterprise",
    topic: "db-security",
    difficulty: 2,
    prompt: "What does encryption in transit protect against?",
    options: [
      { id: "a", text: "Someone reading the data as it crosses the network" },
      { id: "b", text: "Someone stealing the disk the database runs on" },
      { id: "c", text: "An attacker with valid database credentials" },
      { id: "d", text: "A developer querying production by mistake" },
    ],
    answer: "a",
    explanation:
      "In transit covers the wire, at rest covers the disk and backups, and neither does anything about someone who can log in legitimately. Knowing which threat each one addresses is what stops encryption being treated as a single checkbox.",
    concepts: ["Encryption in transit", "Encryption at rest", "Threat model"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-priv-001",
    type: "mcq",
    track: "data-enterprise",
    topic: "data-privacy",
    difficulty: 2,
    prompt: "Why is a data retention policy an engineering concern rather than a legal one?",
    options: [
      {
        id: "a",
        text: "Data is kept forever unless something is built to delete it",
      },
      { id: "b", text: "Engineers decide which laws apply" },
      { id: "c", text: "Retention determines database performance" },
      { id: "d", text: "Legal teams cannot access production systems" },
    ],
    answer: "a",
    explanation:
      "A written policy nobody implemented is not a policy — the default behaviour of every system is to accumulate. Automated expiry is the only version that actually happens, and it is code somebody has to write.",
    concepts: ["Data retention", "Automated expiry", "Data minimisation"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-eid-001",
    type: "mcq",
    track: "data-enterprise",
    topic: "enterprise-identity",
    difficulty: 2,
    prompt: "With SSO, where does the user actually type their password?",
    options: [
      { id: "a", text: "At the identity provider — your application never sees it" },
      { id: "b", text: "In your application, which forwards it for checking" },
      { id: "c", text: "In both, so each can verify independently" },
      { id: "d", text: "Nowhere; SSO replaces passwords entirely" },
    ],
    answer: "a",
    explanation:
      "That is the security win. Your app receives a signed assertion of who the user is and never handles the credential, so a compromise of your application cannot leak passwords for every other system they use.",
    concepts: ["Single sign-on", "Identity provider", "Assertion"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-eint-001",
    type: "mcq",
    track: "data-enterprise",
    topic: "enterprise-integration",
    difficulty: 2,
    prompt: "Why does connecting many systems point-to-point become unmanageable?",
    options: [
      {
        id: "a",
        text: "The number of integrations grows roughly with the square of the systems",
      },
      { id: "b", text: "Each connection consumes a network port" },
      { id: "c", text: "Systems cannot handle more than a few connections" },
      { id: "d", text: "Point-to-point connections cannot be encrypted" },
    ],
    answer: "a",
    explanation:
      "Ten systems each talking to the others is up to forty-five separate integrations, every one with its own format and failure mode. Routing through a shared bus or an event backbone turns that into ten.",
    concepts: ["Point-to-point integration", "Enterprise service bus", "Event backbone"],
    tags: ["fundamentals"],
  },
  {
    id: "ez-tenant-001",
    type: "mcq",
    track: "data-enterprise",
    topic: "multi-tenancy",
    difficulty: 2,
    prompt: "In a shared-schema multi-tenant system, what keeps one customer's data separate from another's?",
    options: [
      {
        id: "a",
        text: "Every query filtering on a tenant identifier — which is why it is enforced in the database where possible",
      },
      { id: "b", text: "Separate database connections per tenant" },
      { id: "c", text: "Encrypting each tenant's rows with a different key" },
      { id: "d", text: "Storing tenants in separate tables" },
    ],
    answer: "a",
    explanation:
      "Isolation rests on a WHERE clause, so forgetting it once is a cross-tenant data leak. That is the argument for row-level security: the rule lives in the database and applies to every query, including the ad-hoc one someone runs at 11pm.",
    concepts: ["Multi-tenancy", "Tenant identifier", "Row-level security"],
    tags: ["fundamentals"],
  },
];
