import type { Question } from "@/content/types";

/** Band 1 and 2 for the six Stage 3 topics on the learning spine: load
 *  balancing, queues, observability, protocols, security, and concurrency.
 *
 *  Third tranche of the easy-question commission. Named for the path stage
 *  rather than the track, because these six sit across three different tracks
 *  and belong together only in the order a learner meets them. */
export const questions: Question[] = [
  {
    id: "ez-lb-001",
    type: "mcq",
    track: "system-design",
    topic: "load-balancing",
    difficulty: 1,
    prompt: "What is a health check, in a load balancer?",
    options: [
      { id: "a", text: "A periodic probe that decides whether a backend still gets traffic" },
      { id: "b", text: "A report of how much CPU and memory each of the backends is using" },
      { id: "c", text: "A test run against the application before it is deployed anywhere" },
      { id: "d", text: "An alert sent to the on-call engineer whenever a backend fails" },
    ],
    answer: "a",
    explanation:
      "It is what makes a load balancer more than a traffic splitter: fail the probe and you stop receiving requests, so a broken instance takes itself out without anyone waking up. The subtlety is what the probe tests — one that only proves the process is running routes users into a broken backend.",
    concepts: ["Health check", "Backend pool", "Liveness probe"],
    tags: ["basics"],
  },
  {
    id: "ez-lb-002",
    type: "mcq",
    track: "system-design",
    topic: "load-balancing",
    difficulty: 2,
    prompt: "Why does adding a load balancer not by itself make a system more available?",
    options: [
      { id: "a", text: "The balancer becomes a single point of failure unless it is redundant too" },
      { id: "b", text: "Balancers add latency, which counts against the availability target" },
      { id: "c", text: "Traffic still reaches one backend at a time, so nothing is duplicated" },
      { id: "d", text: "Load balancers must be configured by hand for each new backend" },
    ],
    answer: "a",
    explanation:
      "You have moved the single point of failure rather than removed it: everything now depends on the balancer. Real setups run several, fronted by DNS or an anycast address, so the balancer tier can lose a node too. Redundancy only helps where you have actually applied it.",
    concepts: ["Single point of failure", "Redundancy", "Load balancer"],
    tags: ["availability"],
  },
  {
    id: "ez-q-001",
    type: "mcq",
    track: "system-design",
    topic: "queues",
    difficulty: 1,
    prompt: "What is a message queue?",
    options: [
      { id: "a", text: "A buffer where work is put now and picked up by a worker later" },
      { id: "b", text: "A database table that records the order requests arrived in" },
      { id: "c", text: "A list of the tasks assigned to each engineer on the team" },
      { id: "d", text: "A protocol two services use to call each other directly" },
    ],
    answer: "a",
    explanation:
      "The defining property is that producing and consuming are separated in time. Whoever asks for the work stops waiting; whoever does it can be slower, restarted, or scaled independently. Everything else about queues — delivery guarantees, ordering, retries — follows from that separation.",
    concepts: ["Message queue", "Producer", "Consumer", "Asynchronous processing"],
    tags: ["basics"],
  },
  {
    id: "ez-q-002",
    type: "mcq",
    track: "system-design",
    topic: "queues",
    difficulty: 2,
    prompt: "What does at-least-once delivery mean for a consumer?",
    options: [
      { id: "a", text: "It may receive the same message more than once and must cope" },
      { id: "b", text: "It will receive every message in the order they were produced" },
      { id: "c", text: "It is guaranteed to receive each message exactly one time" },
      { id: "d", text: "It must acknowledge a message before it starts processing it" },
    ],
    answer: "a",
    explanation:
      "The broker promises not to lose a message and pays for that by sometimes delivering it twice — a network blip during acknowledgement is indistinguishable from a dead worker. Duplicates are therefore certain over a long enough window, and handling them is the consumer's job, not the broker's.",
    concepts: ["At-least-once delivery", "Idempotent consumer", "Acknowledgement"],
    tags: ["delivery"],
  },
  {
    id: "ez-q-003",
    type: "short",
    track: "system-design",
    topic: "queues",
    difficulty: 2,
    context:
      "Messages are arriving faster than the workers can process them, so the number waiting in the queue climbs steadily through the afternoon.",
    prompt:
      "What is this growing count of unprocessed messages called? (Either common name is accepted.)",
    answers: ["backlog", "queue depth", "lag", "consumer lag", "queue backlog", "depth"],
    typoTolerance: true,
    explanation:
      "The backlog, or queue depth. It is the number worth alerting on, because a consumer that is running and healthy while falling steadily behind looks fine on every other dashboard. Watch its age too: depth says whether you are keeping up, age says how stale the oldest item is.",
    concepts: ["Queue depth", "Consumer lag", "Backlog"],
    tags: ["monitoring"],
  },
  {
    id: "ez-obs-002",
    type: "mcq",
    track: "system-design",
    topic: "observability",
    difficulty: 1,
    prompt: "What is a log line for?",
    options: [
      { id: "a", text: "Recording what happened during one specific event or request" },
      { id: "b", text: "Counting how many times something has happened altogether" },
      { id: "c", text: "Measuring how long a given operation took, on average" },
      { id: "d", text: "Alerting a human the moment a threshold has been crossed" },
    ],
    answer: "a",
    explanation:
      "A log is a record of one thing that happened, with enough detail to reconstruct it. That is both its strength and its cost: it answers what happened to this request, and it gets expensive fast at volume. Counting and averaging are what metrics do, far more cheaply.",
    concepts: ["Structured logging", "Metrics", "Observability"],
    tags: ["basics"],
  },
  {
    id: "ez-obs-003",
    type: "mcq",
    track: "system-design",
    topic: "observability",
    difficulty: 2,
    prompt: "Why is average latency a poor thing to alert on?",
    options: [
      { id: "a", text: "It hides the slow tail, where the users who are suffering actually are" },
      { id: "b", text: "It is more expensive to compute than a percentile is" },
      { id: "c", text: "Averages cannot be compared between two different services" },
      { id: "d", text: "It changes too often for a stable threshold to be set against" },
    ],
    answer: "a",
    explanation:
      "An average is dominated by the common case, so a service where most requests take 40ms and one in a hundred takes four seconds still averages well. Those slow requests are somebody's experience — and a page making many backend calls hits them on nearly every load.",
    concepts: ["Tail latency", "p99 latency", "Percentile"],
    tags: ["alerting"],
  },
  {
    id: "ez-obs-004",
    type: "short",
    track: "system-design",
    topic: "observability",
    difficulty: 2,
    context:
      "One request passes through five services. A single view stitches the timings together and shows which of the five spent the time.",
    prompt: "What is this cross-service view of one request called? (Two words.)",
    answers: ["distributed trace", "trace", "distributed tracing", "request trace", "tracing"],
    typoTolerance: true,
    explanation:
      "A distributed trace. Metrics tell you the system is slow and logs tell you what one service did; only a trace tells you which hop of five was responsible. It is the first thing to reach for when latency is up and no single service looks at fault.",
    concepts: ["Distributed tracing", "Span", "Latency breakdown"],
    tags: ["tracing"],
  },
  {
    id: "ez-proto-001",
    type: "mcq",
    track: "system-design",
    topic: "protocols",
    difficulty: 1,
    prompt: "What does HTTPS add over HTTP?",
    options: [
      { id: "a", text: "Encryption in transit, plus proof the server is who it claims to be" },
      { id: "b", text: "Compression of the response body, so that pages load more quickly" },
      { id: "c", text: "A guarantee that the server stores your data securely once at rest" },
      { id: "d", text: "A faster connection, because the protocol version used is newer" },
    ],
    answer: "a",
    explanation:
      "TLS gives you two things: nobody in between can read or alter the traffic, and the certificate proves you reached the server you asked for rather than something impersonating it. It says nothing at all about what happens to your data once it has arrived.",
    concepts: ["TLS", "Encryption in transit", "Certificate authority"],
    tags: ["basics"],
  },
  {
    id: "ez-proto-002",
    type: "mcq",
    track: "system-design",
    topic: "protocols",
    difficulty: 2,
    prompt: "Why does opening a new connection for every request cost so much?",
    options: [
      { id: "a", text: "Each one pays a handshake before any request data can be sent" },
      { id: "b", text: "Each connection uses a separate port that must then be freed" },
      { id: "c", text: "The server has to re-read its configuration for every connection" },
      { id: "d", text: "Connections are limited, so the browser queues them up in order" },
    ],
    answer: "a",
    explanation:
      "TCP costs a round trip to establish and TLS costs one or two more, so on a high-latency link the setup can take longer than the request itself. Keeping the connection open and reusing it removes that cost, which is why HTTP/1.1 does so by default.",
    concepts: ["TCP handshake", "TLS handshake", "HTTP keep-alive", "Round-trip time"],
    tags: ["connections"],
  },
  {
    id: "ez-proto-003",
    type: "matching",
    track: "system-design",
    topic: "protocols",
    difficulty: 2,
    prompt: "Match each protocol to what it is normally used for.",
    pairs: [
      { left: "HTTP", right: "Request and response between a client and a server" },
      { left: "WebSocket", right: "A connection either side can send on at any time" },
      { left: "Server-Sent Events", right: "A one-way stream of updates from server to client" },
      { left: "gRPC", right: "Fast, compact calls between services inside a system" },
      { left: "DNS", right: "Turning a hostname into an address before anything else" },
    ],
    explanation:
      "The choice comes down to who needs to speak and when. Most things are request-and-response and should stay that way; reach for a persistent connection only when the server genuinely needs to push, and prefer the one-way option when the traffic only goes one way.",
    concepts: ["HTTP", "WebSocket", "Server-Sent Events", "gRPC"],
    tags: ["selection"],
  },
  {
    id: "ez-sec-001",
    type: "mcq",
    track: "system-design",
    topic: "security",
    difficulty: 1,
    prompt: "What is authentication?",
    options: [
      { id: "a", text: "Establishing who somebody is, before deciding what they may do" },
      { id: "b", text: "Deciding which actions an already-known user is permitted to take" },
      { id: "c", text: "Encrypting a password so it cannot be read from the database" },
      { id: "d", text: "Checking that a request came from a browser rather than a bot" },
    ],
    answer: "a",
    explanation:
      "Identity first. Authentication answers who you are, authorisation answers whether you may do this — and the HTTP codes follow: 401 means we cannot tell who you are, 403 means we can and you still may not. Conflating them is how an endpoint checks one and not the other.",
    concepts: ["Authentication", "Authorisation", "HTTP 401 Unauthorized"],
    tags: ["basics"],
  },
  {
    id: "ez-sec-002",
    type: "mcq",
    track: "system-design",
    topic: "security",
    difficulty: 2,
    prompt: "Why should a password never be stored as plain text?",
    options: [
      { id: "a", text: "Anyone who reads the database gets every user's password directly" },
      { id: "b", text: "Plain text takes more storage space than a hash of the same value" },
      { id: "c", text: "The database cannot index a column containing plain text passwords" },
      { id: "d", text: "Passwords in plain text cannot be compared quickly at sign-in time" },
    ],
    answer: "a",
    explanation:
      "A breach is not hypothetical, and people reuse passwords — so a leaked plain-text store compromises your users' other accounts too. Store a slow, salted hash from bcrypt, scrypt, or Argon2 and you never hold the password at all, only something an attempt can be checked against.",
    concepts: ["Password hashing", "bcrypt", "Salt", "Credential stuffing"],
    tags: ["passwords"],
  },
  {
    id: "ez-sec-003",
    type: "short",
    track: "system-design",
    topic: "security",
    difficulty: 2,
    context:
      "A service that only ever reads from one table is given a database account that can read that table and nothing else — no writes, no other tables, no schema changes.",
    prompt: "Which security principle is being applied? (Two words.)",
    answers: [
      "least privilege",
      "principle of least privilege",
      "least-privilege",
      "minimum privilege",
    ],
    typoTolerance: true,
    explanation:
      "Least privilege. It does not stop a compromise, it bounds one: whoever takes over that service gets exactly what the service could do and nothing more. The test to apply is what a stolen credential would permit, rather than what the code intends to do with it.",
    concepts: ["Principle of least privilege", "Blast radius", "Database role"],
    tags: ["principles"],
  },
  {
    id: "ez-sec-004",
    type: "multi",
    track: "system-design",
    topic: "security",
    difficulty: 2,
    prompt: "Which are sound ways to handle user input? Select all that apply.",
    options: [
      { id: "a", text: "Validate it against what you expect, and reject anything else" },
      { id: "b", text: "Use parameterised queries so it can never be parsed as SQL" },
      { id: "c", text: "Encode it on output, according to where it is being rendered" },
      { id: "d", text: "Strip out any word from it that looks like a SQL keyword" },
      { id: "e", text: "Trust it once it has passed the browser's own validation" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "Validate on the way in, parameterise at the database, encode on the way out. The rejected two are the classic mistakes: a keyword blocklist is a game you eventually lose, and client-side validation is a convenience for honest users that an attacker skips by calling your API directly.",
    concepts: ["Input validation", "Parameterised query", "Output encoding", "Client-side validation"],
    tags: ["input"],
  },
  {
    id: "ez-conc-003",
    type: "mcq",
    track: "code-craft",
    topic: "concurrency",
    difficulty: 1,
    prompt: "What does it mean for two pieces of work to be concurrent?",
    options: [
      { id: "a", text: "Both are in progress over the same period, interleaved or in parallel" },
      { id: "b", text: "Both are running at the very same instant on separate CPU cores" },
      { id: "c", text: "Both are waiting for the very same resource to become available" },
      { id: "d", text: "Both must finish before either result can be used by anything" },
    ],
    answer: "a",
    explanation:
      "Concurrency is about overlapping lifetimes, not simultaneous execution. A single core switching between two tasks is concurrent and not parallel; two cores running them at once is both. The distinction matters because concurrency is what creates races, with or without a second core.",
    concepts: ["Concurrency", "Parallelism", "Race condition"],
    tags: ["basics"],
  },
  {
    id: "ez-conc-004",
    type: "mcq",
    track: "code-craft",
    topic: "concurrency",
    difficulty: 2,
    prompt: "Why is read-modify-write dangerous when two requests run at once?",
    options: [
      { id: "a", text: "Both can read the old value, so one update overwrites the other" },
      { id: "b", text: "The database will reject the second write as a duplicate value" },
      { id: "c", text: "Reads are slower than writes, so the order cannot be predicted" },
      { id: "d", text: "The second request has to wait, which makes the request time out" },
    ],
    answer: "a",
    explanation:
      "Read a counter as 10, add one, write 11 — and if another request did the same between your read and your write, one increment vanishes. This is a lost update. The fixes all remove the gap: an atomic increment, a conditional write, or a lock around the whole sequence.",
    concepts: ["Lost update", "Read-modify-write", "Atomic operation", "Optimistic locking"],
    tags: ["races"],
  },
  {
    id: "ez-conc-005",
    type: "short",
    track: "code-craft",
    topic: "concurrency",
    difficulty: 2,
    context:
      "Two operations each hold a lock that the other one needs. Neither can continue, neither will release, and both wait for ever.",
    prompt: "What is this situation called? (One word.)",
    answers: ["deadlock", "dead lock", "deadlocked", "deadlocks"],
    typoTolerance: true,
    explanation:
      "A deadlock. It requires a cycle in who is waiting for what, which is why the standard prevention is a rule rather than a clever algorithm: always acquire locks in the same order everywhere. With one global order no cycle can form, so the situation cannot arise.",
    concepts: ["Deadlock", "Lock ordering", "Circular wait"],
    tags: ["locks"],
  },
  {
    id: "ez-conc-006",
    type: "mcq",
    track: "code-craft",
    topic: "concurrency",
    difficulty: 2,
    prompt: "Why is immutable data easier to work with in concurrent code?",
    options: [
      { id: "a", text: "Nothing can change it, so no reader ever needs to lock it first" },
      { id: "b", text: "Immutable data uses less memory, so more of it fits in cache" },
      { id: "c", text: "The compiler runs immutable code on several cores automatically" },
      { id: "d", text: "Immutable values are copied, so each thread gets its own version" },
    ],
    answer: "a",
    explanation:
      "Races require shared state that is also mutable. Take away the mutation and the sharing becomes harmless — any number of threads can read one value with no coordination at all. The cost is producing a new value rather than updating in place, usually cheaper than the locking it replaces.",
    concepts: ["Immutability", "Shared mutable state", "Thread safety"],
    tags: ["immutability"],
  },
];
