import type { Question } from "@/content/types";

/** Band 1 and 2 for the six Stage 4 topics on the learning spine:
 *  consistency, replication, services and boundaries, defending a trade-off,
 *  incidents, and design docs.
 *
 *  Final tranche of the easy-question commission. Stage 4 is where the answer
 *  stops being a fact and starts being a judgement, so the easy band here is
 *  about having the vocabulary to hold the conversation at all -- knowing what
 *  read-your-writes names, or what blameless actually means. */
export const questions: Question[] = [
  {
    id: "ez-cons-003",
    type: "mcq",
    track: "system-design",
    topic: "consistency",
    difficulty: 1,
    prompt: "What does it mean for two replicas to be consistent?",
    options: [
      { id: "a", text: "A read from either one returns the same value at the same moment" },
      { id: "b", text: "Both replicas hold exactly the same amount of data on their disks" },
      { id: "c", text: "Both replicas are running exactly the same version of the software" },
      { id: "d", text: "Writes are applied to both replicas by one and the same process" },
    ],
    answer: "a",
    explanation:
      "Consistency is about what a reader can observe, not about disk usage or software versions. Every consistency model answers the same question: if I write here and read there, what am I promised? They differ only in how strong that promise is, and what it costs to keep.",
    concepts: ["Consistency model", "Replica", "Read-after-write"],
    tags: ["basics"],
  },
  {
    id: "ez-cons-004",
    type: "mcq",
    track: "system-design",
    topic: "consistency",
    difficulty: 2,
    prompt: "Which operation genuinely needs strong consistency?",
    options: [
      { id: "a", text: "Debiting an amount of money from an account balance" },
      { id: "b", text: "Showing how many people have liked a given post" },
      { id: "c", text: "Displaying the profile picture a user has chosen" },
      { id: "d", text: "Recording that a page has been viewed by somebody" },
    ],
    answer: "a",
    explanation:
      "The test is whether two concurrent operations can both succeed and leave a state that is simply wrong. Spend a balance twice and it is wrong; count a like twice and nobody can tell. Reserve the coordination cost for places where being briefly wrong actually costs something.",
    concepts: ["Strong consistency", "Invariant", "Coordination cost"],
    tags: ["choosing"],
  },
  {
    id: "ez-cons-005",
    type: "short",
    track: "system-design",
    topic: "consistency",
    difficulty: 2,
    context:
      "A user posts a comment, the page reloads, and their own comment is missing — because the reload was served by a replica that has not caught up yet.",
    prompt: "Which consistency guarantee would have prevented this? (Three words.)",
    answers: [
      "read-your-writes",
      "read your writes",
      "read-your-own-writes",
      "read your own writes",
      "read-after-write",
    ],
    typoTolerance: true,
    explanation:
      "Read-your-writes. It promises only that you see your own changes, which is far cheaper than promising everyone sees them at once — usually bought by routing that one user to the leader briefly. It is also the anomaly users notice most, because it looks like their action failed.",
    concepts: ["Read-your-writes consistency", "Replication lag", "Session guarantee"],
    tags: ["guarantees"],
  },
  {
    id: "ez-cons-006",
    type: "matching",
    track: "system-design",
    topic: "consistency",
    difficulty: 2,
    prompt: "Match each consistency guarantee to what it promises.",
    pairs: [
      { left: "Strong", right: "Every read returns the most recent write" },
      { left: "Eventual", right: "Replicas converge in time, with no promise of when" },
      { left: "Read-your-writes", right: "You always see your own changes; others may lag" },
      { left: "Monotonic reads", right: "You never see a value go backwards in time" },
    ],
    explanation:
      "These sit on a ladder from expensive to cheap, and the skill is picking per operation rather than per system. The bottom two are session guarantees: they promise something about one user's experience rather than about the whole system, which is exactly why they cost so much less.",
    concepts: ["Strong consistency", "Eventual consistency", "Monotonic reads", "Session guarantee"],
    tags: ["models"],
  },
  {
    id: "ez-repl-002",
    type: "mcq",
    track: "system-design",
    topic: "replication",
    difficulty: 1,
    prompt: "What is a read replica?",
    options: [
      { id: "a", text: "A copy of the database that serves reads but takes no writes" },
      { id: "b", text: "A backup copy of the database taken on a fixed schedule" },
      { id: "c", text: "A cache sitting in front of the database holding the hot rows" },
      { id: "d", text: "A second database that holds a different subset of the data" },
    ],
    answer: "a",
    explanation:
      "It takes read load off the leader, which is often the cheapest scaling move available, because most workloads read far more than they write. It is emphatically not a backup — a replica applies whatever the leader did, including the accidental delete, within seconds.",
    concepts: ["Read replica", "Read scaling", "Leader-follower replication"],
    tags: ["basics"],
  },
  {
    id: "ez-repl-003",
    type: "mcq",
    track: "system-design",
    topic: "replication",
    difficulty: 2,
    prompt: "Why is a replica not a backup?",
    options: [
      { id: "a", text: "It faithfully applies your mistakes too, within seconds of you making them" },
      { id: "b", text: "Replicas store less of the data than the leader does, to save on cost" },
      { id: "c", text: "A replica cannot be restored onto a different machine afterwards" },
      { id: "d", text: "Backups are always encrypted and replicas are not, by convention" },
    ],
    answer: "a",
    explanation:
      "Replication protects you from a machine dying. Backups protect you from a person or a deploy — the DELETE with the missing WHERE reaches every replica almost immediately. You need both, and the only meaningful test of a backup is a restore you have actually performed.",
    concepts: ["Replication", "Backup", "Point-in-time recovery"],
    tags: ["durability"],
  },
  {
    id: "ez-repl-004",
    type: "short",
    track: "system-design",
    topic: "replication",
    difficulty: 2,
    context:
      "A write lands on the leader. For a short window afterwards, a follower asked for that same row still returns the old value.",
    prompt: "What is the size of that window called? (Two words.)",
    answers: ["replication lag", "lag", "replica lag", "replication delay"],
    typoTolerance: true,
    explanation:
      "Replication lag. It is normally milliseconds and it is never zero, which is enough to produce the bug where a user cannot see their own change. It also grows under write load, so the moment you most need replicas current is the moment they are furthest behind.",
    concepts: ["Replication lag", "Asynchronous replication", "Read-your-writes consistency"],
    tags: ["lag"],
  },
  {
    id: "ez-repl-005",
    type: "mcq",
    track: "system-design",
    topic: "replication",
    difficulty: 2,
    prompt: "What does synchronous replication cost that asynchronous does not?",
    options: [
      { id: "a", text: "Every write waits for a follower to confirm before it is done" },
      { id: "b", text: "Twice the storage, because two copies are kept rather than one" },
      { id: "c", text: "Followers can no longer be used to serve read traffic at all" },
      { id: "d", text: "The leader has to be restarted whenever a follower is added" },
    ],
    answer: "a",
    explanation:
      "You buy durability and pay in latency: a confirmed write has definitely reached another machine, and every write now waits for the slowest follower required to acknowledge it. That also means an unreachable follower can stall writes entirely, which is why semi-synchronous setups keep exactly one.",
    concepts: ["Synchronous replication", "Asynchronous replication", "Durability"],
    tags: ["trade-offs"],
  },
  {
    id: "ez-ms-003",
    type: "mcq",
    track: "system-design",
    topic: "microservices",
    difficulty: 1,
    prompt: "What is a monolith?",
    options: [
      { id: "a", text: "One deployable application containing all of the system's features" },
      { id: "b", text: "An application with no automated tests covering any of its code" },
      { id: "c", text: "A codebase that only one team is permitted to make changes to" },
      { id: "d", text: "A very large database that every part of the system writes to" },
    ],
    answer: "a",
    explanation:
      "A monolith is a deployment shape, not a quality judgement: everything ships together as one unit. That is why a well-organised monolith is entirely reasonable and often the right starting point — the modules inside can be as clean as you like, and moving a boundary is a refactor rather than a migration.",
    concepts: ["Monolith", "Modular monolith", "Deployment unit"],
    tags: ["basics"],
  },
  {
    id: "ez-ms-004",
    type: "mcq",
    track: "system-design",
    topic: "microservices",
    difficulty: 2,
    prompt: "What replaces a function call when two services are split apart?",
    options: [
      { id: "a", text: "A network call, which can be slow, fail, or half-succeed" },
      { id: "b", text: "A database query run against the other service's own tables" },
      { id: "c", text: "A shared library that both services import at build time" },
      { id: "d", text: "A configuration file listing where the other service lives" },
    ],
    answer: "a",
    explanation:
      "This is the whole trade in one sentence. A function call either returns or throws; a network call can also time out, return late, or succeed at the far end while the response is lost. Every timeout, retry, and circuit breaker in a distributed system exists because of that third case.",
    concepts: ["Network call", "Partial failure", "Timeout"],
    tags: ["cost"],
  },
  {
    id: "ez-ms-005",
    type: "short",
    track: "system-design",
    topic: "microservices",
    difficulty: 2,
    context:
      "One slow service causes its callers to pile up waiting, which makes them slow, which makes their callers pile up. Within minutes most of the system is down.",
    prompt: "What is this spreading failure called? (Two words.)",
    answers: [
      "cascading failure",
      "cascade",
      "cascading failures",
      "failure cascade",
      "cascade failure",
    ],
    typoTolerance: true,
    explanation:
      "A cascading failure. Note that it starts with something slow rather than something down: an outright failure returns fast and frees the caller, while a slow dependency holds threads open. That is why timeouts matter more than retries — they turn somebody else's outage into your degraded response.",
    concepts: ["Cascading failure", "Timeout", "Circuit breaker", "Thread pool exhaustion"],
    tags: ["failure"],
  },
  {
    id: "ez-ms-006",
    type: "mcq",
    track: "system-design",
    topic: "microservices",
    difficulty: 2,
    prompt: "Why should each service own its own data?",
    options: [
      { id: "a", text: "Sharing a table couples the teams, so neither can change it alone" },
      { id: "b", text: "Separate databases are cheaper to run than one larger database" },
      { id: "c", text: "A service can only open connections to one database at a time" },
      { id: "d", text: "Query performance improves when tables live in smaller databases" },
    ],
    answer: "a",
    explanation:
      "A shared table is a shared contract. Neither team can alter it without coordinating, so you get the deployment overhead and network latency of separate services with none of the independence that was the point. Own your data and expose it through an interface you can version.",
    concepts: ["Shared database antipattern", "Service boundary", "Schema coupling"],
    tags: ["boundaries"],
  },
  {
    id: "ez-trade-003",
    type: "mcq",
    track: "communication",
    topic: "tradeoffs",
    difficulty: 1,
    prompt: "What does it mean to call something a trade-off?",
    options: [
      { id: "a", text: "You gain one thing by giving up another, on purpose" },
      { id: "b", text: "Two options are equally good, so the choice does not matter" },
      { id: "c", text: "A decision has to be made before all the facts are known" },
      { id: "d", text: "The cheaper option was chosen because of a budget limit" },
    ],
    answer: "a",
    explanation:
      "The two halves matter equally. Naming only the gain is a sales pitch; naming only the cost is an objection. A trade-off states both and says why the exchange is worth it here — which is also what makes the decision reviewable later, once the circumstances have moved.",
    concepts: ["Trade-off", "Design rationale", "Decision record"],
    tags: ["basics"],
  },
  {
    id: "ez-trade-004",
    type: "mcq",
    track: "communication",
    topic: "tradeoffs",
    difficulty: 2,
    prompt: "Why is 'it depends' a weak answer on its own?",
    options: [
      { id: "a", text: "It is true but says nothing, because it names no thing it depends on" },
      { id: "b", text: "It suggests the speaker has not encountered the problem before" },
      { id: "c", text: "Technical questions almost always do have one correct answer" },
      { id: "d", text: "It takes longer to say than simply committing to an option" },
    ],
    answer: "a",
    explanation:
      "The phrase is right and unfinished. What makes it an answer is the next sentence: it depends on whether reads dominate, on whether stale data is acceptable, on how large the team is. Name the variable and you have shown judgement; stop there and you have shown hesitation.",
    concepts: ["Conditional reasoning", "Decision dependency", "Hedging"],
    tags: ["answering"],
  },
  {
    id: "ez-trade-005",
    type: "multi",
    track: "communication",
    topic: "tradeoffs",
    difficulty: 2,
    prompt:
      "What makes a design decision easy to revisit later? Select all that apply.",
    options: [
      { id: "a", text: "The reason it was made is written down somewhere findable" },
      { id: "b", text: "What was considered and rejected is recorded alongside it" },
      { id: "c", text: "The conditions that would change the answer are named too" },
      { id: "d", text: "The decision was made by the most senior person available" },
      { id: "e", text: "The implementation was kept deliberately hard to change" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "A decision you cannot reconstruct is one you argue from scratch every time somebody new asks. Recording the rejected options is what stops the same alternative being re-proposed annually, and naming what would change your mind turns a preference into something testable.",
    concepts: ["Architecture decision record", "Design rationale", "Reversibility"],
    tags: ["recording"],
  },
  {
    id: "ez-inc-002",
    type: "mcq",
    track: "workplace",
    topic: "incidents",
    difficulty: 1,
    prompt: "What is the first priority during a live incident?",
    options: [
      { id: "a", text: "Stopping the impact on users, before understanding the cause" },
      { id: "b", text: "Finding the root cause, so that the right fix can be applied" },
      { id: "c", text: "Telling everyone affected that the team is aware of the issue" },
      { id: "d", text: "Recording what happened so that the postmortem will be accurate" },
    ],
    answer: "a",
    explanation:
      "Mitigate, then diagnose. Rolling back or disabling the change ends user impact in seconds, and the evidence is still there afterwards. Every minute spent understanding first is a minute of impact you could already have stopped — the ordering people invert under pressure, because understanding feels responsible.",
    concepts: ["Mitigation before diagnosis", "Rollback", "Incident response"],
    tags: ["basics"],
  },
  {
    id: "ez-inc-003",
    type: "mcq",
    track: "workplace",
    topic: "incidents",
    difficulty: 2,
    prompt: "What does a blameless postmortem actually mean?",
    options: [
      { id: "a", text: "Asking how the system let it happen, rather than who did it" },
      { id: "b", text: "Not writing down which people were involved in the incident" },
      { id: "c", text: "Accepting that some incidents have no cause worth chasing" },
      { id: "d", text: "Reviewing the incident without the people who responded to it" },
    ],
    answer: "a",
    explanation:
      "Blameless does not mean nameless. The question moves from the person to the conditions: why was a single command able to do this, why did review pass, why did alerting take eleven minutes. Punish somebody for an outage and the next one gets hidden, which is how organisations stop learning.",
    concepts: ["Blameless postmortem", "Systemic failure", "Psychological safety"],
    tags: ["postmortems"],
  },
  {
    id: "ez-inc-004",
    type: "short",
    track: "workplace",
    topic: "incidents",
    difficulty: 2,
    context:
      "During an incident one person coordinates: deciding what to try next, keeping everyone else informed, and deliberately not debugging anything themselves.",
    prompt: "What is this role called? (Two words.)",
    answers: ["incident commander", "commander", "incident lead", "incident manager"],
    typoTolerance: true,
    explanation:
      "The incident commander. Their value is that they are not debugging — with no clear owner, three people investigate the same thing while nobody decides and nobody communicates. The role is coordination, and handing it over explicitly is what stops a long incident degrading as people tire.",
    concepts: ["Incident commander", "Incident roles", "Coordination"],
    tags: ["roles"],
  },
  {
    id: "ez-doc-003",
    type: "mcq",
    track: "workplace",
    topic: "design-docs",
    difficulty: 1,
    prompt: "When is a design doc most useful?",
    options: [
      { id: "a", text: "Before the work starts, while changing direction is still cheap" },
      { id: "b", text: "After the work is finished, as a record of what got built" },
      { id: "c", text: "During the work, updated continuously as things are decided" },
      { id: "d", text: "Only when a change is large enough to need approval from above" },
    ],
    answer: "a",
    explanation:
      "The value is the feedback, and feedback is worth most when acting on it costs least. A doc written afterwards is documentation, which is useful for something else entirely. If the design is already built, you are asking for review of a decision nobody can now change.",
    concepts: ["Design document", "Cost of change", "Early feedback"],
    tags: ["timing"],
  },
  {
    id: "ez-doc-004",
    type: "mcq",
    track: "workplace",
    topic: "design-docs",
    difficulty: 2,
    prompt: "Why does a design doc need an 'alternatives considered' section?",
    options: [
      { id: "a", text: "It shows the choice was made rather than defaulted into" },
      { id: "b", text: "It makes the document longer and therefore more thorough" },
      { id: "c", text: "It gives reviewers something to comment on besides the design" },
      { id: "d", text: "It is required before an architecture review will be scheduled" },
    ],
    answer: "a",
    explanation:
      "Without it a reader cannot tell whether you weighed the obvious cheaper option or never thought of it — and the second is what they will assume. It also saves the same alternative being re-proposed every year, because the reason it was rejected is on the record.",
    concepts: ["Alternatives considered", "Design rationale", "Decision record"],
    tags: ["sections"],
  },
  {
    id: "ez-doc-005",
    type: "short",
    track: "workplace",
    topic: "design-docs",
    difficulty: 2,
    context:
      "A section near the top lists what the work deliberately will not do — features considered and set aside, cases left unhandled on purpose.",
    prompt: "What is this section conventionally called? (Two words.)",
    answers: ["non-goals", "non goals", "nongoals", "out of scope", "non-goal"],
    typoTolerance: true,
    explanation:
      "Non-goals. It is the cheapest scope control there is: a reader who knows what you are not doing stops asking for it and stops assuming it was forgotten. It protects you later too, when somebody treats an omission as an oversight rather than a decision you wrote down.",
    concepts: ["Non-goals", "Scope creep", "Design document"],
    tags: ["scope"],
  },
  {
    id: "ez-doc-006",
    type: "multi",
    track: "workplace",
    topic: "design-docs",
    difficulty: 2,
    prompt: "What should a design doc contain? Select all that apply.",
    options: [
      { id: "a", text: "The problem, stated before any solution is proposed" },
      { id: "b", text: "What is explicitly out of scope for this piece of work" },
      { id: "c", text: "The alternatives weighed, and why they were not chosen" },
      { id: "d", text: "Every class and method the implementation will contain" },
      { id: "e", text: "An estimate of how many lines of code it will take" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "A design doc argues for a decision; it is not a specification of the code. Listing every class ages badly within a week of implementation starting, and gives a reviewer nothing to push back on. What they can usefully review is the problem, the boundary, and the reasoning.",
    concepts: ["Design document", "Non-goals", "Alternatives considered"],
    tags: ["contents"],
  },
];
