import type { Question } from "@/content/types";

/** Band 1 and 2 for the Frontend, DSA, and Communication lanes.
 *
 *  Lane topics are held to four easy questions rather than the spine's six.
 *  A lane is reached after two stages by somebody who has already shown they
 *  can answer things, so a session reaching into band 3 to fill itself is a
 *  different proposition from doing that to a beginner on their first day.
 *  Four still covers a five-question session without repeating the same one
 *  every time. */
export const questions: Question[] = [
  {
    id: "ez-fearch-002",
    type: "mcq",
    track: "frontend",
    topic: "frontend-architecture",
    difficulty: 1,
    prompt: "What is a component, in a frontend framework?",
    options: [
      { id: "a", text: "A reusable piece of interface with its own markup and behaviour" },
      { id: "b", text: "A single file holding all of the styles used by one page" },
      { id: "c", text: "A function that fetches data before the page is rendered" },
      { id: "d", text: "A route that maps one URL onto the screen it should show" },
    ],
    answer: "a",
    explanation:
      "The unit of composition: markup, behaviour, and usually styling bundled behind a name and a set of inputs. What makes it useful is the boundary — you can reason about one component without holding the rest of the page in your head, and reuse it without copying it.",
    concepts: ["Component", "Composition", "Props"],
    tags: ["basics"],
  },
  {
    id: "ez-fearch-003",
    type: "mcq",
    track: "frontend",
    topic: "frontend-architecture",
    difficulty: 2,
    prompt: "Why does moving state higher up the component tree cause problems?",
    options: [
      { id: "a", text: "Every component between the owner and the user of it must pass it down" },
      { id: "b", text: "State stored higher in the tree is lost whenever the route changes" },
      { id: "c", text: "Components higher in the tree re-render more slowly than lower ones" },
      { id: "d", text: "Frameworks limit how many state values one component may hold" },
    ],
    answer: "a",
    explanation:
      "This is prop drilling: the intermediate components neither use nor care about the value, and they all have to change when its shape does. Keep state as low as the components reading it allow, and lift it only when something above genuinely needs it.",
    concepts: ["Prop drilling", "State colocation", "Context"],
    tags: ["state"],
  },
  {
    id: "ez-feperf-002",
    type: "mcq",
    track: "frontend",
    topic: "frontend-performance",
    difficulty: 2,
    prompt: "Why is a large JavaScript bundle worse than an image of the same size?",
    options: [
      { id: "a", text: "The image is decoded off the main thread; the script must be parsed and run" },
      { id: "b", text: "Images are always compressed and JavaScript bundles never are" },
      { id: "c", text: "Browsers download scripts more slowly than they download images" },
      { id: "d", text: "Scripts cannot be cached between visits the way that images can" },
    ],
    answer: "a",
    explanation:
      "A megabyte of image costs a megabyte of download. A megabyte of JavaScript costs the download, then parsing, then compiling, then executing — all on the main thread, which is also the thread that responds to taps. That is why bundle size shows up as unresponsiveness.",
    concepts: ["Main thread", "Parse and compile time", "Bundle size", "Interaction to Next Paint"],
    tags: ["bundles"],
  },
  {
    id: "ez-fesec-002",
    type: "mcq",
    track: "frontend",
    topic: "frontend-security",
    difficulty: 1,
    prompt: "What is a cookie?",
    options: [
      { id: "a", text: "A small value the browser stores and sends back to that site" },
      { id: "b", text: "A file the server writes into the user's downloads folder" },
      { id: "c", text: "A cached copy of a page, kept ready for the next visit" },
      { id: "d", text: "An identifier assigned by the network to each connection" },
    ],
    answer: "a",
    explanation:
      "Small, scoped to a site, and sent automatically on every request to it — which is exactly what makes it useful for sessions and exactly what makes CSRF possible. Because the browser attaches it without being asked, a request forged by another site carries it too.",
    concepts: ["Cookie", "Session", "Cross-site request forgery"],
    tags: ["basics"],
  },
  {
    id: "ez-fesec-003",
    type: "mcq",
    track: "frontend",
    topic: "frontend-security",
    difficulty: 2,
    prompt: "Why is user input dangerous when written straight into a page?",
    options: [
      { id: "a", text: "The browser will run any script tags it finds, as if you wrote them" },
      { id: "b", text: "Long input can break the layout and hide the rest of the content" },
      { id: "c", text: "The input may contain characters that the database cannot store" },
      { id: "d", text: "Search engines will index whatever the user happened to type" },
    ],
    answer: "a",
    explanation:
      "The browser cannot tell your markup from somebody else's. That is cross-site scripting, and the fix is encoding on output rather than filtering on input — the same string is harmless in a database and dangerous in an HTML attribute, so it is escaped where the context is known.",
    concepts: ["Cross-site scripting", "Output encoding", "Content Security Policy"],
    tags: ["xss"],
  },
  {
    id: "ez-pat-004",
    type: "mcq",
    track: "dsa-concepts",
    topic: "patterns",
    difficulty: 1,
    prompt: "What is an algorithmic pattern?",
    options: [
      { id: "a", text: "A shape of problem that a known approach reliably solves" },
      { id: "b", text: "A rule about how source code in a team should be laid out" },
      { id: "c", text: "A sequence of steps that solves one particular problem" },
      { id: "d", text: "A measure of how much memory an algorithm will consume" },
    ],
    answer: "a",
    explanation:
      "Patterns are about recognition rather than memorisation. 'Longest contiguous run satisfying a condition' is a sliding window whatever the problem is dressed up as, and spotting that in ten seconds is what separates people who solve these from people who stare at them.",
    concepts: ["Pattern recognition", "Sliding window", "Problem shape"],
    tags: ["basics"],
  },
  {
    id: "ez-pat-005",
    type: "matching",
    track: "dsa-concepts",
    topic: "patterns",
    difficulty: 2,
    prompt: "Match each phrase in a problem to the approach it hints at.",
    pairs: [
      { left: "Sorted array, find a target", right: "Binary search" },
      { left: "Longest or smallest contiguous run", right: "Sliding window" },
      { left: "All combinations or arrangements", right: "Backtracking" },
      { left: "Shortest path in an unweighted graph", right: "Breadth-first search" },
      { left: "The kth largest of many values", right: "A heap of size k" },
    ],
    explanation:
      "These phrases are the tell, and they survive whatever story the problem is wrapped in. Saying the pattern out loud before writing anything is also what turns a silent twenty minutes into a conversation the person opposite can actually help with.",
    concepts: ["Binary search", "Sliding window", "Backtracking", "Breadth-first search"],
    tags: ["recognition"],
  },
  {
    id: "ez-st-002",
    type: "mcq",
    track: "dsa-concepts",
    topic: "space-time",
    difficulty: 2,
    prompt: "When is precomputing an answer the wrong choice?",
    options: [
      { id: "a", text: "When the underlying data changes more often than it is read" },
      { id: "b", text: "When the computation takes longer than a millisecond to run" },
      { id: "c", text: "When the result is too large to hold in a single variable" },
      { id: "d", text: "When more than one part of the code needs the same answer" },
    ],
    answer: "a",
    explanation:
      "Precomputation pays when reads outnumber writes, because every write invalidates the stored answer. Flip that ratio and you are doing the work anyway, plus maintaining a copy that is usually stale. The question is never how expensive the computation is, but how often it would be repeated.",
    concepts: ["Precomputation", "Cache invalidation", "Read-write ratio"],
    tags: ["when-not-to"],
  },
  {
    id: "ez-scope-001",
    type: "mcq",
    track: "communication",
    topic: "scoping",
    difficulty: 1,
    prompt: "Why ask questions before designing anything?",
    options: [
      { id: "a", text: "The requirements decide the design, and you have not heard them yet" },
      { id: "b", text: "It shows the interviewer that you are engaged with the problem" },
      { id: "c", text: "It gives you time to think about the solution while you talk" },
      { id: "d", text: "Most problems have a standard answer once they are classified" },
    ],
    answer: "a",
    explanation:
      "'Design Twitter' is not a question, it is an invitation to ask them. Ten thousand users and ten million are different systems, and building for the wrong one is not a smaller mistake for having been made confidently. The questions are the work, not the preamble to it.",
    concepts: ["Requirements gathering", "Scoping", "Ambiguity"],
    tags: ["basics"],
  },
  {
    id: "ez-scope-002",
    type: "multi",
    track: "communication",
    topic: "scoping",
    difficulty: 2,
    prompt: "Which answers actually change a design? Select all that apply.",
    options: [
      { id: "a", text: "How many users there are, and how active they are" },
      { id: "b", text: "How stale the data is allowed to become" },
      { id: "c", text: "How bad it is if the system is down for an hour" },
      { id: "d", text: "Which programming language the team prefers" },
      { id: "e", text: "What the feature will be called in the interface" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "Each of the three rules something out: scale decides whether one database suffices, staleness decides whether caching is available to you, and downtime tolerance decides how much redundancy is worth paying for. Language and naming are real decisions that leave the architecture where it was.",
    concepts: ["Non-functional requirements", "Scoping", "Design constraint"],
    tags: ["questions"],
  },
  {
    id: "ez-aud-002",
    type: "mcq",
    track: "communication",
    topic: "audience",
    difficulty: 1,
    prompt: "What should decide how much detail an explanation contains?",
    options: [
      { id: "a", text: "What the listener needs in order to make their decision" },
      { id: "b", text: "How much you happen to know about the subject yourself" },
      { id: "c", text: "How long you have been given to deliver the explanation" },
      { id: "d", text: "How complicated the underlying system happens to be" },
    ],
    answer: "a",
    explanation:
      "Start from what they have to do with the information. An engineer joining your team needs the failure modes; a director approving spend needs the cost and the risk. Same system, different explanation — and the commonest mistake is explaining at the level you find interesting.",
    concepts: ["Audience adaptation", "Abstraction level", "Technical translation"],
    tags: ["basics"],
  },
  {
    id: "ez-aud-003",
    type: "mcq",
    track: "communication",
    topic: "audience",
    difficulty: 2,
    prompt: "What is the risk in explaining with an analogy?",
    options: [
      { id: "a", text: "Every analogy breaks somewhere, and they will follow it past that point" },
      { id: "b", text: "Analogies take longer to deliver than a direct explanation would" },
      { id: "c", text: "A listener may feel the subject is being oversimplified for them" },
      { id: "d", text: "Analogies cannot be used for anything that is genuinely technical" },
    ],
    answer: "a",
    explanation:
      "An analogy transfers a mental model, including the parts that do not apply. 'A database index is like a book index' works right up until somebody asks about writes. Say where it stops when you introduce it — one sentence, and it prevents a confident wrong conclusion built on your words.",
    concepts: ["Analogy", "Mental model", "Abstraction leak"],
    tags: ["analogies"],
  },
  {
    id: "ez-dis-003",
    type: "mcq",
    track: "communication",
    topic: "disagreement",
    difficulty: 1,
    prompt: "What makes a technical objection more likely to be heard?",
    options: [
      { id: "a", text: "Being specific about what would go wrong, and when" },
      { id: "b", text: "Raising it in front of as many people as possible" },
      { id: "c", text: "Stating it with as much confidence as you can manage" },
      { id: "d", text: "Waiting until the decision has been made to raise it" },
    ],
    answer: "a",
    explanation:
      "'This will not scale' is an opinion; 'this does one database write per message and we expect ten thousand a second' is a claim somebody can check. Specificity gives the other person something to engage with, and it means being wrong costs you nothing — you learn the number.",
    concepts: ["Falsifiable claim", "Constructive disagreement", "Specificity"],
    tags: ["basics"],
  },
  {
    id: "ez-dis-004",
    type: "mcq",
    track: "communication",
    topic: "disagreement",
    difficulty: 2,
    prompt: "What does 'disagree and commit' mean in practice?",
    options: [
      { id: "a", text: "Say what you think, then support the decision fully once it is made" },
      { id: "b", text: "Agree publicly while continuing to argue the point privately" },
      { id: "c", text: "Let the disagreement go without ever having voiced it at all" },
      { id: "d", text: "Commit to revisiting the decision at some fixed date later" },
    ],
    answer: "a",
    explanation:
      "Both halves are load-bearing. Committing without disagreeing wastes the judgement you were hired for; disagreeing without committing makes you the reason it fails. What makes the commitment honest is a tripwire — a metric agreed in advance that would reopen it.",
    concepts: ["Disagree and commit", "Tripwire", "Team trust"],
    tags: ["commitment"],
  },
  {
    id: "ez-est-002",
    type: "mcq",
    track: "workplace",
    topic: "estimation",
    difficulty: 1,
    prompt: "Why is an estimate given as a range more useful than a single number?",
    options: [
      { id: "a", text: "It communicates how uncertain you are, which the number hides" },
      { id: "b", text: "It gives you more room to finish later than you had promised" },
      { id: "c", text: "A range is easier to calculate than one precise figure is" },
      { id: "d", text: "It transfers responsibility for the deadline to whoever asked" },
    ],
    answer: "a",
    explanation:
      "'Three weeks' and 'two to five weeks' are different claims, and only one is honest about what you know. The range is also what lets somebody else decide how much buffer the commitment needs — a decision belonging to whoever owns the promise, rather than to you.",
    concepts: ["Estimation range", "Uncertainty", "Estimate versus commitment"],
    tags: ["ranges"],
  },
];
