import type { Question } from "@/content/types";

/** Band 1 and 2 for the six Stage 2 topics on the learning spine: debugging,
 *  code review, SQL joins, caching, CI/CD, and complexity analysis.
 *
 *  Second tranche of the easy-question commission. Same reason as Stage 1:
 *  the bank was authored middle-out, so a path that opens on fundamentals had
 *  two or three easy questions per topic to work with. MCQ option lengths are
 *  held close together so the longest option is not the answer. */
export const questions: Question[] = [
  {
    id: "ez-dbg-001",
    type: "mcq",
    track: "workplace",
    topic: "debugging",
    difficulty: 1,
    prompt: "What does it mean to reproduce a bug?",
    options: [
      { id: "a", text: "Making the failure happen on demand, so you can tell when it is fixed" },
      { id: "b", text: "Writing down the steps a user took before the failure occurred" },
      { id: "c", text: "Copying the error message into the ticket for the next person" },
      { id: "d", text: "Running the whole test suite to find out what else is broken too" },
    ],
    answer: "a",
    explanation:
      "A bug you cannot make happen on demand is one you cannot prove you have fixed — the failure stopping might be your change or might be luck. Reproducing it first is also how most causes surface, because narrowing the steps forces you to work out which conditions actually matter.",
    concepts: ["Reproduction", "Minimal reproducible example", "Debugging method"],
    tags: ["basics"],
  },
  {
    id: "ez-dbg-002",
    type: "short",
    track: "workplace",
    topic: "debugging",
    difficulty: 2,
    context:
      "An error report includes the chain of function calls that were open at the moment the failure happened, innermost first.",
    prompt: "What is this list of open calls called? (Two words.)",
    answers: ["stack trace", "stacktrace", "call stack", "traceback", "stack traceback"],
    typoTolerance: true,
    explanation:
      "A stack trace. It answers how execution got here, which is usually more useful than the error text itself. Read from the top for where it broke, then scan down for the first line in your own code — that frame is where you can actually change something.",
    concepts: ["Stack trace", "Call stack", "Exception"],
    tags: ["terminology"],
  },
  {
    id: "ez-dbg-003",
    type: "multi",
    track: "workplace",
    topic: "debugging",
    difficulty: 2,
    prompt: "Which make a bug easier to find? Select all that apply.",
    options: [
      { id: "a", text: "A smaller reproduction, with the steps that do not matter removed" },
      { id: "b", text: "Knowing what changed in the system since it last worked" },
      { id: "c", text: "A hypothesis specific enough to be proved wrong by a test" },
      { id: "d", text: "Adding a log line to every function across the codebase" },
      { id: "e", text: "Changing several things at once so you get there faster" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "Each of the three shrinks the search space. The two rejected options grow it: logging everywhere buries the signal, and changing several things at once means a fix that works leaves you unsure which change did it, so you cannot safely undo the other two.",
    concepts: ["Minimal reproducible example", "Change one variable at a time", "Falsifiable hypothesis"],
    tags: ["method"],
  },
  {
    id: "ez-cr-001",
    type: "mcq",
    track: "workplace",
    topic: "code-review",
    difficulty: 1,
    prompt: "What is a code review for?",
    options: [
      { id: "a", text: "Catching problems before they ship, and spreading knowledge of the code" },
      { id: "b", text: "Checking that the formatting matches the project's agreed style guide" },
      { id: "c", text: "Recording who approved a change in case something goes wrong later" },
      { id: "d", text: "Confirming that the author has run the tests before they merge it" },
    ],
    answer: "a",
    explanation:
      "Two jobs, and the second is the one people forget: a review is often the only time anyone else reads that code before it becomes something they have to maintain. Formatting belongs to a linter, and the approval record is a side effect rather than the point.",
    concepts: ["Code review", "Knowledge sharing", "Linting"],
    tags: ["basics"],
  },
  {
    id: "ez-cr-002",
    type: "mcq",
    track: "workplace",
    topic: "code-review",
    difficulty: 2,
    prompt: "Why is a smaller pull request usually reviewed better?",
    options: [
      { id: "a", text: "Attention runs out, so past a certain size defects stop being found" },
      { id: "b", text: "Small changes are less likely to contain a bug in the first place" },
      { id: "c", text: "Reviewers are required to read every line of a small change" },
      { id: "d", text: "The tools display small diffs faster than they display large ones" },
    ],
    answer: "a",
    explanation:
      "Defect detection falls off sharply with size: a fifty-line change gets read, a two-thousand-line one gets an approval. The change is not safer for being small — it is better reviewed. That is why 'can this be split?' is often the most valuable comment, said before the work is done.",
    concepts: ["Pull request size", "Defect detection rate", "Review fatigue"],
    tags: ["size"],
  },
  {
    id: "ez-join-001",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-joins",
    difficulty: 1,
    prompt: "What does a JOIN do in SQL?",
    options: [
      { id: "a", text: "Combines rows from two tables using a condition that relates them" },
      { id: "b", text: "Merges two tables permanently into a single stored table" },
      { id: "c", text: "Appends the rows of one table onto the end of another one" },
      { id: "d", text: "Copies a column from one table across into a second table" },
    ],
    answer: "a",
    explanation:
      "A join matches rows across tables on a condition, usually a key appearing in both, and returns the combined row. Nothing is written — the result exists only for that query. Stacking rows on top of each other is UNION, a different operation with different rules.",
    concepts: ["JOIN", "Foreign key", "UNION"],
    tags: ["basics"],
  },
  {
    id: "ez-join-002",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-joins",
    difficulty: 2,
    prompt: "What is the difference between an INNER JOIN and a LEFT JOIN?",
    options: [
      { id: "a", text: "LEFT keeps every row from the left table, filling NULLs where none match" },
      { id: "b", text: "LEFT reads the left table first, which makes the query run faster" },
      { id: "c", text: "LEFT permits joining on a column that has no index on it" },
      { id: "d", text: "LEFT returns the rows in the order the left table stores them" },
    ],
    answer: "a",
    explanation:
      "INNER discards a row when nothing matches; LEFT keeps it and fills the right-hand columns with NULL. That distinction is the whole point — 'customers and their orders, including customers with none' is a LEFT JOIN, and getting it wrong silently drops the rows you were counting.",
    concepts: ["INNER JOIN", "LEFT JOIN", "NULL semantics"],
    tags: ["join-types"],
  },
  {
    id: "ez-join-003",
    type: "short",
    track: "sql-analytics",
    topic: "sql-joins",
    difficulty: 2,
    context:
      "An orders table holds a customer_id column. Every value in it must match the id of a real row in the customers table, and the database refuses any insert that breaks that.",
    prompt: "What is this kind of column constraint called? (Two words.)",
    answers: ["foreign key", "foreign-key", "fk", "foreign key constraint"],
    typoTolerance: true,
    explanation:
      "A foreign key. It is what makes a join meaningful rather than hopeful: the database guarantees the reference points at something real, so you cannot end up with an order belonging to a customer who does not exist — nor delete that customer while the order still refers to them.",
    concepts: ["Foreign key", "Referential integrity", "JOIN"],
    tags: ["constraints"],
  },
  {
    id: "ez-join-004",
    type: "mcq",
    track: "sql-analytics",
    topic: "sql-joins",
    difficulty: 2,
    context:
      "A query joins customers to orders and returns far more rows than there are customers.",
    prompt: "Why does joining customers to orders return more rows than customers?",
    options: [
      { id: "a", text: "Each customer matched several orders, so their row repeats per match" },
      { id: "b", text: "The join condition was written round the wrong way in the ON clause" },
      { id: "c", text: "The customers table already contains duplicated rows in it" },
      { id: "d", text: "A LEFT JOIN was used where an INNER JOIN was what was needed" },
    ],
    answer: "a",
    explanation:
      "A one-to-many join multiplies rows by design: one customer with four orders becomes four rows. That is correct, and it is also how revenue totals get inflated, because summing a customer-level column now counts it four times. Aggregate the many side first if you need one row each.",
    concepts: ["Join fan-out", "Row multiplication", "Cardinality"],
    tags: ["fan-out"],
  },
  {
    id: "ez-cache-001",
    type: "mcq",
    track: "system-design",
    topic: "caching",
    difficulty: 2,
    prompt: "Why can a cache serve data that is out of date?",
    options: [
      { id: "a", text: "It holds a copy taken earlier, and the original may have changed since" },
      { id: "b", text: "Caches store their data in a compressed form that loses precision" },
      { id: "c", text: "The cache and the database disagree about what the current time is" },
      { id: "d", text: "Reads from a cache are never permitted to check against the source" },
    ],
    answer: "a",
    explanation:
      "Staleness is not a fault, it is the trade. A cache is fast precisely because it answers without asking the source, and the price is a window in which the copy and the original disagree. Every caching decision is really a decision about how long that window may be.",
    concepts: ["Cache staleness", "TTL", "System of record"],
    tags: ["staleness"],
  },
  {
    id: "ez-ci-002",
    type: "mcq",
    track: "delivery",
    topic: "ci-cd",
    difficulty: 1,
    prompt: "What runs in a continuous integration pipeline?",
    options: [
      { id: "a", text: "The checks that decide whether a change is safe to merge" },
      { id: "b", text: "The deployment of the change into the production environment" },
      { id: "c", text: "The code review comments that the rest of the team left" },
      { id: "d", text: "A record of who approved the change before it was merged" },
    ],
    answer: "a",
    explanation:
      "Continuous integration is about merging safely and often: build, tests, linting, type checks — whatever has to pass before a change joins the main line. Deploying that change is continuous delivery or deployment, a separate stage with its own decision about when it runs.",
    concepts: ["Continuous integration", "Build pipeline", "Merge gate"],
    tags: ["basics"],
  },
  {
    id: "ez-ci-003",
    type: "short",
    track: "delivery",
    topic: "ci-cd",
    difficulty: 2,
    context:
      "The pipeline builds the application once, then promotes that exact same output through staging and into production rather than rebuilding at each step.",
    prompt: "What is the built output being promoted called? (One word.)",
    answers: ["artefact", "artifact", "build artefact", "build artifact", "the artefact"],
    typoTolerance: true,
    explanation:
      "An artefact. Building once and promoting the same bytes is what makes staging a real test: rebuild per environment and the thing you tested is not the thing you shipped, and the difference between the two is exactly where the surprise lives.",
    concepts: ["Build artefact", "Build once, deploy many", "Immutable artefact"],
    tags: ["artefacts"],
  },
  {
    id: "ez-ci-004",
    type: "mcq",
    track: "delivery",
    topic: "ci-cd",
    difficulty: 2,
    prompt: "Why should a pipeline run its fastest checks first?",
    options: [
      { id: "a", text: "A broken change fails in seconds rather than after the slow stages" },
      { id: "b", text: "Fast checks tend to find more defects than the slower ones do" },
      { id: "c", text: "Running them in that order uses fewer build minutes overall" },
      { id: "d", text: "Slow checks cannot start until the fast ones have all passed" },
    ],
    answer: "a",
    explanation:
      "The cost of a pipeline is not compute, it is how long somebody waits to learn they were wrong. Linting and unit tests in the first minute means an obvious mistake is caught before a ten-minute integration suite runs. It saves the compute too, but that is the smaller win.",
    concepts: ["Fail fast", "Pipeline stage", "Feedback loop"],
    tags: ["ordering"],
  },
  {
    id: "ez-ci-005",
    type: "multi",
    track: "delivery",
    topic: "ci-cd",
    difficulty: 2,
    prompt:
      "Which belong in a pipeline rather than in a person's head? Select all that apply.",
    options: [
      { id: "a", text: "Running the whole test suite on every proposed change" },
      { id: "b", text: "Checking that formatting and lint rules are satisfied" },
      { id: "c", text: "Building the exact artefact that will later be deployed" },
      { id: "d", text: "Deciding whether the feature is worth building at all" },
      { id: "e", text: "Judging whether the design fits the rest of the codebase" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "Automate what is mechanical and repeatable, and save human attention for judgement. A person checking formatting is a person not reading the logic — which is the real argument for linting, rather than any claim that consistent braces matter in themselves.",
    concepts: ["Automated checks", "Merge gate", "Code review"],
    tags: ["automation"],
  },
  {
    id: "ez-cx-001",
    type: "mcq",
    track: "dsa-concepts",
    topic: "complexity",
    difficulty: 1,
    prompt: "What does Big-O notation describe?",
    options: [
      { id: "a", text: "How the cost of an algorithm grows as the input gets larger" },
      { id: "b", text: "How long an algorithm takes to run, measured in milliseconds" },
      { id: "c", text: "How much memory an algorithm needs for a given input size" },
      { id: "d", text: "How many lines of code an implementation requires to write" },
    ],
    answer: "a",
    explanation:
      "Growth, not time. Big-O says how cost scales with n and deliberately ignores constants and hardware, which is what lets it compare two approaches before either is written. It applies to memory as readily as to time — you just have to say which you mean.",
    concepts: ["Big-O notation", "Asymptotic growth", "Space complexity"],
    tags: ["basics"],
  },
  {
    id: "ez-cx-002",
    type: "matching",
    track: "dsa-concepts",
    topic: "complexity",
    difficulty: 2,
    prompt: "Match each operation to its typical cost.",
    pairs: [
      { left: "Looking a key up in a hash map", right: "Constant time on average" },
      { left: "Binary search in a sorted array", right: "Logarithmic in the number of items" },
      { left: "Scanning every item in a list", right: "Linear in the number of items" },
      { left: "Comparing every pair of items", right: "Quadratic in the number of items" },
      { left: "Sorting a list by comparison", right: "Linearithmic, or n log n" },
    ],
    explanation:
      "These five cover most of what you need to reason about a solution out loud. The gap that matters in practice is between linear and quadratic: at a thousand items that is a thousand steps against a million, which is the difference between instant and unusable.",
    concepts: ["Big-O notation", "Binary search", "Hash table", "Linearithmic time"],
    tags: ["costs"],
  },
];
