import type { Question } from "@/content/types";

/** Band 1 and 2 for the six Stage 1 topics on the learning spine: version
 *  control, testing, code quality, databases, API design, error handling.
 *
 *  These exist because a fundamentals-first path needs depth at the bottom of
 *  the difficulty range, and the bank was authored middle-out -- 170 easy
 *  questions across 67 core topics is not enough to build an early stage on.
 *  MCQ option lengths are kept within a few characters of each other here, so
 *  the longest option is not the answer. */
export const questions: Question[] = [
  {
    id: "ez-vcs-001",
    type: "mcq",
    track: "delivery",
    topic: "version-control",
    difficulty: 1,
    prompt: "What does a version control system give a team?",
    options: [
      { id: "a", text: "A shared history of every change, and a way to work in parallel" },
      { id: "b", text: "A nightly backup copy of whatever files are on each machine" },
      { id: "c", text: "A way to run the tests automatically before every release" },
      { id: "d", text: "A record of who is currently assigned to each open task" },
    ],
    answer: "a",
    explanation:
      "Two things at once: you can see what changed, when, and why; and several people can work on one codebase without overwriting each other. Backups, continuous integration, and issue tracking are separate tools that happen to sit near it in most workflows.",
    concepts: ["Version control", "Commit history", "Branching"],
    tags: ["basics"],
  },
  {
    id: "ez-vcs-002",
    type: "short",
    track: "delivery",
    topic: "version-control",
    difficulty: 2,
    context:
      "You want to build a feature over several days without your half-finished work affecting anyone else, and without holding up their releases.",
    prompt: "What do you create to isolate work in progress from the main line? (One word.)",
    answers: ["branch", "a branch", "feature branch", "branches"],
    typoTolerance: true,
    explanation:
      "A branch. It gives you a private line of history to commit onto, so unfinished work is saved and shared only when you choose. The cost is that the longer it lives, the further it drifts from main and the harder the eventual merge becomes.",
    concepts: ["Branch", "Merge conflict", "Trunk-based development"],
    tags: ["branching"],
  },
  {
    id: "ez-vcs-003",
    type: "mcq",
    track: "delivery",
    topic: "version-control",
    difficulty: 2,
    prompt: "Why commit small and often rather than once at the end?",
    options: [
      { id: "a", text: "Each commit is a point you can return to, and small ones read easily" },
      { id: "b", text: "The repository uses less disk space with more frequent commits" },
      { id: "c", text: "Git runs measurably faster when each commit changes fewer files" },
      { id: "d", text: "Only the most recent commit is kept, so committing often matters" },
    ],
    answer: "a",
    explanation:
      "A commit is a checkpoint. Small ones let you revert precisely, review meaningfully, and find the change that broke something with git bisect. One enormous commit at the end leaves a single all-or-nothing point to return to, which is barely better than none.",
    concepts: ["Atomic commit", "git bisect", "Commit history"],
    tags: ["commits"],
  },
  {
    id: "ez-vcs-004",
    type: "matching",
    track: "delivery",
    topic: "version-control",
    difficulty: 1,
    prompt: "Match each Git command to what it does.",
    pairs: [
      { left: "git clone", right: "Copies a remote repository onto your machine" },
      { left: "git commit", right: "Records your staged changes in the local history" },
      { left: "git push", right: "Sends your local commits to the remote repository" },
      { left: "git pull", right: "Fetches others' commits and merges them into yours" },
      { left: "git branch", right: "Lists or creates lines of development" },
    ],
    explanation:
      "The pair worth separating is commit and push. Committing is local and costs nothing; pushing publishes. Work that is committed but never pushed exists on one machine only, which is where a surprising amount of lost work goes.",
    concepts: ["git commit", "git push", "Remote repository"],
    tags: ["commands"],
  },
  {
    id: "ez-test-001",
    type: "mcq",
    track: "delivery",
    topic: "testing",
    difficulty: 1,
    prompt: "What is an automated test for?",
    options: [
      { id: "a", text: "It checks that the code still behaves as intended, with nobody watching" },
      { id: "b", text: "It measures how quickly the application responds to each request" },
      { id: "c", text: "It documents the code so that new joiners understand it faster" },
      { id: "d", text: "It finds security problems in the libraries a project depends on" },
    ],
    answer: "a",
    explanation:
      "A test encodes an expectation and checks it on demand. The value is repetition: it runs on every change, so a behaviour someone relied on last year still works today. Performance, documentation, and dependency scanning are real needs served by different tools.",
    concepts: ["Automated test", "Regression", "Continuous integration"],
    tags: ["basics"],
  },
  {
    id: "ez-test-002",
    type: "matching",
    track: "delivery",
    topic: "testing",
    difficulty: 2,
    prompt: "Match each kind of test to what it covers.",
    pairs: [
      { left: "Unit test", right: "One function or class, with its dependencies replaced" },
      { left: "Integration test", right: "Components working together, often with a real database" },
      { left: "End-to-end test", right: "A whole user journey through the running application" },
      { left: "Smoke test", right: "A quick check that a deployed build is not obviously broken" },
    ],
    explanation:
      "They trade speed against confidence in opposite directions. Unit tests are fast and prove little about the system as a whole; end-to-end tests prove the most and are slow and flaky enough that you want few of them. That gradient is why the pyramid has its shape.",
    concepts: ["Unit test", "Integration test", "End-to-end test", "Test pyramid"],
    tags: ["kinds"],
  },
  {
    id: "ez-test-003",
    type: "mcq",
    track: "delivery",
    topic: "testing",
    difficulty: 2,
    prompt: "Why write a test that fails before you write the fix?",
    options: [
      { id: "a", text: "A test that has never failed has not been shown to detect anything" },
      { id: "b", text: "Tests written first run measurably quicker than tests written after" },
      { id: "c", text: "Most frameworks require a failing test before accepting a new one" },
      { id: "d", text: "It reserves the test name so that nobody writes a duplicate of it" },
    ],
    answer: "a",
    explanation:
      "Watching it fail is the only evidence the test is wired to the thing it claims to check. A test written against code that already works passes immediately, and one that would also pass against a broken implementation asserts nothing — which stays invisible until the bug ships.",
    concepts: ["Test-driven development", "Assertion strength", "Regression test"],
    tags: ["tdd"],
  },
  {
    id: "ez-test-004",
    type: "short",
    track: "delivery",
    topic: "testing",
    difficulty: 1,
    context:
      "A feature that worked last month stops working after an unrelated change ships.",
    prompt: "What is a previously working behaviour breaking again called? (One word.)",
    answers: ["regression", "a regression", "regressions"],
    typoTolerance: true,
    explanation:
      "A regression. It is the failure mode a test suite exists to catch, because nobody re-checks last month's features by hand before every release. The habit that pays: when you fix one, add the test that would have caught it.",
    concepts: ["Regression", "Regression test", "Test suite"],
    tags: ["terminology"],
  },
  {
    id: "ez-qual-003",
    type: "mcq",
    track: "code-craft",
    topic: "code-quality",
    difficulty: 1,
    prompt: "What makes a name in code a good one?",
    options: [
      { id: "a", text: "It says what the thing is for, so a reader need not look it up" },
      { id: "b", text: "It is short, because shorter names keep lines within the limit" },
      { id: "c", text: "It encodes the variable's type, such as strList for a list" },
      { id: "d", text: "It matches the name of the database column it came from" },
    ],
    answer: "a",
    explanation:
      "Naming is the cheapest documentation there is, and the only kind that cannot go stale without the compiler noticing. If a name needs a comment to explain it, the comment is doing the name's job. Type prefixes restate what the language already enforces.",
    concepts: ["Naming", "Self-documenting code", "Hungarian notation"],
    tags: ["naming"],
  },
  {
    id: "ez-qual-004",
    type: "mcq",
    track: "code-craft",
    topic: "code-quality",
    difficulty: 2,
    prompt: "What does refactoring mean, precisely?",
    options: [
      { id: "a", text: "Changing how code is structured without changing what it does" },
      { id: "b", text: "Rewriting a component from scratch with a cleaner design" },
      { id: "c", text: "Cleaning up formatting and naming across an entire file" },
      { id: "d", text: "Improving performance without altering the observable output" },
    ],
    answer: "a",
    explanation:
      "The definition is strict and worth holding to: behaviour stays identical, structure changes. That is what lets you refactor under a green test suite and trust the result. A rewrite changes behaviour by accident, and optimising changes performance — both need more than a passing suite.",
    concepts: ["Refactoring", "Behaviour preservation", "Rewrite"],
    tags: ["definition"],
  },
  {
    id: "ez-qual-005",
    type: "multi",
    track: "code-craft",
    topic: "code-quality",
    difficulty: 2,
    prompt: "Which are signs a function has grown too big? Select all that apply.",
    options: [
      { id: "a", text: "You cannot say what it does without using the word 'and'" },
      { id: "b", text: "It needs a comment part-way through to introduce the next part" },
      { id: "c", text: "Testing one of its behaviours means setting up all the others" },
      { id: "d", text: "It is longer than the twenty-line limit the team agreed on" },
      { id: "e", text: "It calls more than three other functions to do its work" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "Each of the three points at one function holding several responsibilities. A line limit mistakes symptom for cause: a thirty-line function doing one thing is fine, and a ten-line one doing three is not. Counting calls measures composition, which is the thing you wanted.",
    concepts: ["Single Responsibility principle", "Cohesion", "Extract Method"],
    tags: ["smells"],
  },
  {
    id: "ez-qual-006",
    type: "short",
    track: "code-craft",
    topic: "code-quality",
    difficulty: 2,
    context:
      "Duplicated blocks, a parameter list nobody can remember, a class that changes for four unrelated reasons. None is a bug, and each suggests the design is wrong somewhere.",
    prompt: "What is the general name for a surface symptom like this? (Two words.)",
    answers: ["code smell", "smell", "code smells", "design smell"],
    typoTolerance: true,
    explanation:
      "A code smell. The word is deliberate: it signals something worth investigating rather than something definitely wrong. That distinction matters, because treating every smell as a defect produces churn, and ignoring all of them produces a codebase nobody wants to touch.",
    concepts: ["Code smell", "Refactoring", "Technical debt"],
    tags: ["terminology"],
  },
  {
    id: "ez-db-001",
    type: "mcq",
    track: "system-design",
    topic: "databases",
    difficulty: 2,
    prompt: "Why does a query without an index get slower as the table grows?",
    options: [
      { id: "a", text: "It reads every row to find the matches, so work grows with the table" },
      { id: "b", text: "The database caches fewer rows in memory as the table gets bigger" },
      { id: "c", text: "Larger tables are split across more files, which adds disk seeks" },
      { id: "d", text: "The query planner takes longer to choose a plan on a big table" },
    ],
    answer: "a",
    explanation:
      "Without an index the engine performs a full table scan, so cost is proportional to row count — fine at a thousand rows, unusable at ten million. An index is a sorted structure that lets it jump to the matches instead, which is why the fix is structural rather than tuning.",
    concepts: ["Full table scan", "Database index", "B-tree index"],
    tags: ["indexes"],
  },
  {
    id: "ez-db-002",
    type: "matching",
    track: "system-design",
    topic: "databases",
    difficulty: 2,
    prompt: "Match each part of ACID to what it promises.",
    pairs: [
      { left: "Atomicity", right: "All the operations apply, or none of them do" },
      { left: "Consistency", right: "The database is left obeying its own constraints" },
      { left: "Isolation", right: "Concurrent transactions do not see each other's partial work" },
      { left: "Durability", right: "Once committed, it survives a crash or a power loss" },
    ],
    explanation:
      "Atomicity and durability are the two people rely on daily without naming them: money never leaves one account without arriving in the other, and a confirmed order is still there after a restart. Isolation is the one with settings, and most engines default below full serialisability.",
    concepts: ["ACID", "Atomicity", "Durability", "Transaction isolation"],
    tags: ["acid"],
  },
  {
    id: "ez-db-003",
    type: "mcq",
    track: "system-design",
    topic: "databases",
    difficulty: 2,
    prompt: "What is a primary key for?",
    options: [
      { id: "a", text: "It identifies each row uniquely, so other rows can refer to it" },
      { id: "b", text: "It defines the order rows are physically written to disk" },
      { id: "c", text: "It marks the column the database should index before others" },
      { id: "d", text: "It sets the column that new rows are sorted by when read" },
    ],
    answer: "a",
    explanation:
      "Uniqueness plus a stable handle. Without one you cannot reliably point at a row from another table, update exactly one record, or tell two identical-looking rows apart. Some engines do cluster storage by primary key, but that is an implementation choice rather than the definition.",
    concepts: ["Primary key", "Foreign key", "Clustered index"],
    tags: ["keys"],
  },
  {
    id: "ez-db-004",
    type: "multi",
    track: "system-design",
    topic: "databases",
    difficulty: 2,
    prompt:
      "Which rules belong in the database rather than in application code? Select all that apply.",
    options: [
      { id: "a", text: "An order must always reference a customer that exists" },
      { id: "b", text: "An email address must be unique across all users" },
      { id: "c", text: "A stored quantity can never be a negative number" },
      { id: "d", text: "Which discount campaign is running this week" },
      { id: "e", text: "How a price should be formatted before display" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "Rules the data must always satisfy belong where the data lives, because the database is the one thing every writer passes through — a script, a migration, and a second service are all caught by it. Rules that change with the business, or that concern presentation, belong in code.",
    concepts: ["Database constraint", "Referential integrity", "Unique constraint", "Business rule"],
    tags: ["constraints"],
  },
  {
    id: "ez-api-001",
    type: "mcq",
    track: "system-design",
    topic: "api-design",
    difficulty: 1,
    prompt: "What is an API?",
    options: [
      { id: "a", text: "A defined way for one program to ask another to do something" },
      { id: "b", text: "A user interface generated automatically from a database" },
      { id: "c", text: "A protocol for sending data securely across the internet" },
      { id: "d", text: "A library of functions bundled with a programming language" },
    ],
    answer: "a",
    explanation:
      "An interface between programs rather than between a program and a person. The word covers a library's public functions as much as an HTTP endpoint — what makes it an API is that it is a published contract somebody else writes against, so changing it breaks them.",
    concepts: ["Application programming interface", "Interface contract", "Coupling"],
    tags: ["basics"],
  },
  {
    id: "ez-api-002",
    type: "mcq",
    track: "system-design",
    topic: "api-design",
    difficulty: 2,
    prompt: "What does a 200 status code tell the client?",
    options: [
      { id: "a", text: "The request was understood and processed successfully" },
      { id: "b", text: "The request arrived but has not been processed yet" },
      { id: "c", text: "The response body is guaranteed to contain some data" },
      { id: "d", text: "The server is healthy and accepting further requests" },
    ],
    answer: "a",
    explanation:
      "200 means this specific request succeeded, and nothing more. It says nothing about the server's general health, and a successful response can legitimately carry an empty body or an empty list. 202 is the code for accepted-but-not-finished, which is a different promise.",
    concepts: ["HTTP 200 OK", "HTTP 202 Accepted", "Status code"],
    tags: ["status-codes"],
  },
  {
    id: "ez-api-003",
    type: "short",
    track: "system-design",
    topic: "api-design",
    difficulty: 2,
    context:
      "A public API renames one field in its response. Every client reading that field stops working the same afternoon.",
    prompt: "What is a change that stops existing callers working called? (Two words.)",
    answers: ["breaking change", "a breaking change", "breaking", "breaking changes"],
    typoTolerance: true,
    explanation:
      "A breaking change. It is defined by its effect on callers rather than by how large the edit was — renaming one field breaks people, adding twenty does not. That asymmetry is why API guidance reduces to one rule: you may add, you may not remove or rename.",
    concepts: ["Breaking change", "Backwards compatibility", "API contract"],
    tags: ["evolution"],
  },
  {
    id: "ez-api-004",
    type: "ordering",
    track: "system-design",
    topic: "api-design",
    difficulty: 2,
    prompt: "Put the journey of an HTTP request in order.",
    items: [
      "The client resolves the hostname to a network address",
      "It opens a connection and sends the request line and headers",
      "The server routes the request to the code that handles it",
      "That code runs and produces a status code and a body",
      "The response travels back, and the client reads the status first",
    ],
    explanation:
      "Worth holding in your head, because every layer you will later add — a CDN, a load balancer, a cache — inserts itself at a specific point in this sequence. Knowing where a thing sits tells you what it can and cannot see about the request.",
    concepts: ["HTTP request", "DNS resolution", "Status code"],
    tags: ["http"],
  },
  {
    id: "ez-err-002",
    type: "mcq",
    track: "code-craft",
    topic: "error-handling",
    difficulty: 1,
    prompt: "What is an exception?",
    options: [
      { id: "a", text: "A signal that something went wrong, interrupting normal flow" },
      { id: "b", text: "A special value returned when a function cannot compute" },
      { id: "c", text: "A log entry written when an application behaves unusually" },
      { id: "d", text: "A rule that stops invalid data being saved to a database" },
    ],
    answer: "a",
    explanation:
      "An exception unwinds the call stack until something catches it, and that is what separates it from a returned error value: the caller cannot ignore it by accident. It is the strongest argument for exceptions, and the argument against them is the same property seen from the other side.",
    concepts: ["Exception", "Result type", "Call stack"],
    tags: ["basics"],
  },
  {
    id: "ez-err-003",
    type: "mcq",
    track: "code-craft",
    topic: "error-handling",
    difficulty: 2,
    prompt: "Why is catching an exception and doing nothing so damaging?",
    options: [
      { id: "a", text: "The program carries on in a state its author never planned for" },
      { id: "b", text: "Catching an exception is slower than letting it propagate up" },
      { id: "c", text: "The exception will be raised again the next time it is reached" },
      { id: "d", text: "It prevents the logging framework from recording any output" },
    ],
    answer: "a",
    explanation:
      "The failure does not go away, it goes quiet. Execution continues past the point where an assumption broke, so the damage surfaces later, somewhere unrelated, with nothing connecting it to the cause. An empty catch block turns a clear crash into a mystery.",
    concepts: ["Swallowing exceptions", "Fail fast", "Silent failure"],
    tags: ["antipatterns"],
  },
  {
    id: "ez-err-004",
    type: "multi",
    track: "code-craft",
    topic: "error-handling",
    difficulty: 2,
    prompt:
      "Which details belong only in the log, never in the message a user sees? Select all that apply.",
    options: [
      { id: "a", text: "The stack trace and the line that raised the error" },
      { id: "b", text: "The name and version of the framework in use" },
      { id: "c", text: "The internal hostname of the service that failed" },
      { id: "d", text: "A short description of what the user could try next" },
      { id: "e", text: "A reference id the user can quote to support" },
    ],
    answers: ["a", "b", "c"],
    explanation:
      "The test is whether the reader can act on it. Internals help whoever is debugging and hand an attacker a map of your stack, so they stay in the log. A user needs a next step and a reference — and the reference is what lets support join their report to the log entry.",
    concepts: ["Information disclosure", "Correlation id", "Structured logging"],
    tags: ["messages"],
  },
  {
    id: "ez-err-005",
    type: "short",
    track: "code-craft",
    topic: "error-handling",
    difficulty: 2,
    context:
      "A product page's recommendation panel fails to load. Rather than failing the whole page, the server renders everything else and leaves that panel out.",
    prompt: "What is this way of handling a non-critical failure called? (Two words.)",
    answers: ["graceful degradation", "degradation", "degrade gracefully", "graceful degrade"],
    typoTolerance: true,
    explanation:
      "Graceful degradation. It requires deciding in advance which dependencies are critical and which are decoration, because the code has to know which failures to absorb. Treating every dependency as critical is how one optional widget takes down a checkout page.",
    concepts: ["Graceful degradation", "Critical dependency", "Fallback"],
    tags: ["resilience"],
  },
];
